// Code generated by ent, DO NOT EDIT.

package dictitem

import (
	"blog-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldID, id))
}

// DictType applies equality check predicate on the "dictType" field. It's identical to DictTypeEQ.
func DictType(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldDictType, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldValue, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldCode, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldEnabled, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldSort, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// DictTypeEQ applies the EQ predicate on the "dictType" field.
func DictTypeEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldDictType, v))
}

// DictTypeNEQ applies the NEQ predicate on the "dictType" field.
func DictTypeNEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldDictType, v))
}

// DictTypeIn applies the In predicate on the "dictType" field.
func DictTypeIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldDictType, vs...))
}

// DictTypeNotIn applies the NotIn predicate on the "dictType" field.
func DictTypeNotIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldDictType, vs...))
}

// DictTypeGT applies the GT predicate on the "dictType" field.
func DictTypeGT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldDictType, v))
}

// DictTypeGTE applies the GTE predicate on the "dictType" field.
func DictTypeGTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldDictType, v))
}

// DictTypeLT applies the LT predicate on the "dictType" field.
func DictTypeLT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldDictType, v))
}

// DictTypeLTE applies the LTE predicate on the "dictType" field.
func DictTypeLTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldDictType, v))
}

// DictTypeContains applies the Contains predicate on the "dictType" field.
func DictTypeContains(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContains(FieldDictType, v))
}

// DictTypeHasPrefix applies the HasPrefix predicate on the "dictType" field.
func DictTypeHasPrefix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasPrefix(FieldDictType, v))
}

// DictTypeHasSuffix applies the HasSuffix predicate on the "dictType" field.
func DictTypeHasSuffix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasSuffix(FieldDictType, v))
}

// DictTypeEqualFold applies the EqualFold predicate on the "dictType" field.
func DictTypeEqualFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEqualFold(FieldDictType, v))
}

// DictTypeContainsFold applies the ContainsFold predicate on the "dictType" field.
func DictTypeContainsFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContainsFold(FieldDictType, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldValue, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasSuffix(FieldCode, v))
}

// CodeIsNil applies the IsNil predicate on the "code" field.
func CodeIsNil() predicate.DictItem {
	return predicate.DictItem(sql.FieldIsNull(FieldCode))
}

// CodeNotNil applies the NotNil predicate on the "code" field.
func CodeNotNil() predicate.DictItem {
	return predicate.DictItem(sql.FieldNotNull(FieldCode))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContainsFold(FieldCode, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.DictItem {
	return predicate.DictItem(sql.FieldContainsFold(FieldLabel, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldEnabled, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldSort, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.DictItem {
	return predicate.DictItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DictItem) predicate.DictItem {
	return predicate.DictItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DictItem) predicate.DictItem {
	return predicate.DictItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DictItem) predicate.DictItem {
	return predicate.DictItem(sql.NotPredicates(p))
}
