// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DictItemsColumns holds the columns for the "dictItems" table.
	DictItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "dictType", Type: field.TypeString, Size: 64},
		{Name: "value", Type: field.TypeInt},
		{Name: "label", Type: field.TypeString, Size: 64},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort", Type: field.TypeInt, Default: 100},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
	}
	// DictItemsTable holds the schema information for the "dictItems" table.
	DictItemsTable = &schema.Table{
		Name:       "dictItems",
		Columns:    DictItemsColumns,
		PrimaryKey: []*schema.Column{DictItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "ukDictItemsTypeValue",
				Unique:  true,
				Columns: []*schema.Column{DictItemsColumns[1], DictItemsColumns[2]},
			},
			{
				Name:    "idxDictItemsTypeEnabledSort",
				Unique:  false,
				Columns: []*schema.Column{DictItemsColumns[1], DictItemsColumns[4], DictItemsColumns[5]},
			},
		},
	}
	// OperationLogsColumns holds the columns for the "operationLogs" table.
	OperationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "userId", Type: field.TypeUint64},
		{Name: "username", Type: field.TypeString, Size: 64},
		{Name: "actionValue", Type: field.TypeInt},
		{Name: "actionLabel", Type: field.TypeString, Size: 64},
		{Name: "ip", Type: field.TypeString, Size: 64},
		{Name: "region", Type: field.TypeString, Size: 128, Default: "未知区域"},
		{Name: "userAgent", Type: field.TypeString, Size: 512, Default: ""},
		{Name: "createdAt", Type: field.TypeTime},
	}
	// OperationLogsTable holds the schema information for the "operationLogs" table.
	OperationLogsTable = &schema.Table{
		Name:       "operationLogs",
		Columns:    OperationLogsColumns,
		PrimaryKey: []*schema.Column{OperationLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "operationlogCreatedAt",
				Unique:  false,
				Columns: []*schema.Column{OperationLogsColumns[8]},
			},
			{
				Name:    "operationlogUserId",
				Unique:  false,
				Columns: []*schema.Column{OperationLogsColumns[1]},
			},
			{
				Name:    "operationlogActionValue",
				Unique:  false,
				Columns: []*schema.Column{OperationLogsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "passwordHash", Type: field.TypeString, Size: 255},
		{Name: "nickname", Type: field.TypeString, Size: 64},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 512, Default: ""},
		{Name: "email", Type: field.TypeString, Unique: true, Nullable: true, Size: 128},
		{Name: "status", Type: field.TypeString, Size: 32, Default: "active"},
		{Name: "lastLoginAt", Type: field.TypeTime, Nullable: true},
		{Name: "createdAt", Type: field.TypeTime},
		{Name: "updatedAt", Type: field.TypeTime},
		{Name: "deletedAt", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DictItemsTable,
		OperationLogsTable,
		UsersTable,
	}
)

func init() {
	DictItemsTable.Annotation = &entsql.Annotation{
		Table: "dictItems",
	}
	OperationLogsTable.Annotation = &entsql.Annotation{
		Table: "operationLogs",
	}
}
