// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/comment"
	"blog-server/internal/ent/post"
	"blog-server/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommentCreate is the builder for creating a Comment entity.
type CommentCreate struct {
	config
	mutation *CommentMutation
	hooks    []Hook
}

// SetPostId sets the "postId" field.
func (_c *CommentCreate) SetPostId(v uint64) *CommentCreate {
	_c.mutation.SetPostId(v)
	return _c
}

// SetParentId sets the "parentId" field.
func (_c *CommentCreate) SetParentId(v uint64) *CommentCreate {
	_c.mutation.SetParentId(v)
	return _c
}

// SetNillableParentId sets the "parentId" field if the given value is not nil.
func (_c *CommentCreate) SetNillableParentId(v *uint64) *CommentCreate {
	if v != nil {
		_c.SetParentId(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *CommentCreate) SetNickname(v string) *CommentCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *CommentCreate) SetEmail(v string) *CommentCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *CommentCreate) SetNillableEmail(v *string) *CommentCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetWebsite sets the "website" field.
func (_c *CommentCreate) SetWebsite(v string) *CommentCreate {
	_c.mutation.SetWebsite(v)
	return _c
}

// SetNillableWebsite sets the "website" field if the given value is not nil.
func (_c *CommentCreate) SetNillableWebsite(v *string) *CommentCreate {
	if v != nil {
		_c.SetWebsite(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *CommentCreate) SetContent(v string) *CommentCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CommentCreate) SetStatus(v string) *CommentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CommentCreate) SetNillableStatus(v *string) *CommentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *CommentCreate) SetIP(v string) *CommentCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetUserAgent sets the "userAgent" field.
func (_c *CommentCreate) SetUserAgent(v string) *CommentCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "userAgent" field if the given value is not nil.
func (_c *CommentCreate) SetNillableUserAgent(v *string) *CommentCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetAdminUserId sets the "adminUserId" field.
func (_c *CommentCreate) SetAdminUserId(v uint64) *CommentCreate {
	_c.mutation.SetAdminUserId(v)
	return _c
}

// SetNillableAdminUserId sets the "adminUserId" field if the given value is not nil.
func (_c *CommentCreate) SetNillableAdminUserId(v *uint64) *CommentCreate {
	if v != nil {
		_c.SetAdminUserId(*v)
	}
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *CommentCreate) SetCreatedAt(v time.Time) *CommentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *CommentCreate) SetNillableCreatedAt(v *time.Time) *CommentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updatedAt" field.
func (_c *CommentCreate) SetUpdatedAt(v time.Time) *CommentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updatedAt" field if the given value is not nil.
func (_c *CommentCreate) SetNillableUpdatedAt(v *time.Time) *CommentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deletedAt" field.
func (_c *CommentCreate) SetDeletedAt(v time.Time) *CommentCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deletedAt" field if the given value is not nil.
func (_c *CommentCreate) SetNillableDeletedAt(v *time.Time) *CommentCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CommentCreate) SetID(v uint64) *CommentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPostID sets the "post" edge to the Post entity by ID.
func (_c *CommentCreate) SetPostID(id uint64) *CommentCreate {
	_c.mutation.SetPostID(id)
	return _c
}

// SetPost sets the "post" edge to the Post entity.
func (_c *CommentCreate) SetPost(v *Post) *CommentCreate {
	return _c.SetPostID(v.ID)
}

// SetParentID sets the "parent" edge to the Comment entity by ID.
func (_c *CommentCreate) SetParentID(id uint64) *CommentCreate {
	_c.mutation.SetParentID(id)
	return _c
}

// SetNillableParentID sets the "parent" edge to the Comment entity by ID if the given value is not nil.
func (_c *CommentCreate) SetNillableParentID(id *uint64) *CommentCreate {
	if id != nil {
		_c = _c.SetParentID(*id)
	}
	return _c
}

// SetParent sets the "parent" edge to the Comment entity.
func (_c *CommentCreate) SetParent(v *Comment) *CommentCreate {
	return _c.SetParentID(v.ID)
}

// AddReplyIDs adds the "replies" edge to the Comment entity by IDs.
func (_c *CommentCreate) AddReplyIDs(ids ...uint64) *CommentCreate {
	_c.mutation.AddReplyIDs(ids...)
	return _c
}

// AddReplies adds the "replies" edges to the Comment entity.
func (_c *CommentCreate) AddReplies(v ...*Comment) *CommentCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddReplyIDs(ids...)
}

// SetAdminID sets the "admin" edge to the User entity by ID.
func (_c *CommentCreate) SetAdminID(id uint64) *CommentCreate {
	_c.mutation.SetAdminID(id)
	return _c
}

// SetNillableAdminID sets the "admin" edge to the User entity by ID if the given value is not nil.
func (_c *CommentCreate) SetNillableAdminID(id *uint64) *CommentCreate {
	if id != nil {
		_c = _c.SetAdminID(*id)
	}
	return _c
}

// SetAdmin sets the "admin" edge to the User entity.
func (_c *CommentCreate) SetAdmin(v *User) *CommentCreate {
	return _c.SetAdminID(v.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (_c *CommentCreate) Mutation() *CommentMutation {
	return _c.mutation
}

// Save creates the Comment in the database.
func (_c *CommentCreate) Save(ctx context.Context) (*Comment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CommentCreate) SaveX(ctx context.Context) *Comment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CommentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := comment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := comment.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := comment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := comment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CommentCreate) check() error {
	if _, ok := _c.mutation.PostId(); !ok {
		return &ValidationError{Name: "postId", err: errors.New(`ent: missing required field "Comment.postId"`)}
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "Comment.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := comment.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "Comment.nickname": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := comment.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Comment.email": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Website(); ok {
		if err := comment.WebsiteValidator(v); err != nil {
			return &ValidationError{Name: "website", err: fmt.Errorf(`ent: validator failed for field "Comment.website": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Comment.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := comment.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Comment.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Comment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := comment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Comment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Comment.ip"`)}
	}
	if v, ok := _c.mutation.IP(); ok {
		if err := comment.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Comment.ip": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAgent(); ok {
		if err := comment.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "userAgent", err: fmt.Errorf(`ent: validator failed for field "Comment.userAgent": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Comment.createdAt"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updatedAt", err: errors.New(`ent: missing required field "Comment.updatedAt"`)}
	}
	if len(_c.mutation.PostIDs()) == 0 {
		return &ValidationError{Name: "post", err: errors.New(`ent: missing required edge "Comment.post"`)}
	}
	return nil
}

func (_c *CommentCreate) sqlSave(ctx context.Context) (*Comment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CommentCreate) createSpec() (*Comment, *sqlgraph.CreateSpec) {
	var (
		_node = &Comment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(comment.Table, sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(comment.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(comment.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.Website(); ok {
		_spec.SetField(comment.FieldWebsite, field.TypeString, value)
		_node.Website = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(comment.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(comment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(comment.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(comment.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(comment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(comment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(comment.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.PostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.PostTable,
			Columns: []string{comment.PostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PostId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.ParentTable,
			Columns: []string{comment.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentId = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RepliesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   comment.RepliesTable,
			Columns: []string{comment.RepliesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(comment.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.AdminTable,
			Columns: []string{comment.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdminUserId = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CommentCreateBulk is the builder for creating many Comment entities in bulk.
type CommentCreateBulk struct {
	config
	err      error
	builders []*CommentCreate
}

// Save creates the Comment entities in the database.
func (_c *CommentCreateBulk) Save(ctx context.Context) ([]*Comment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Comment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CommentCreateBulk) SaveX(ctx context.Context) []*Comment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CommentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CommentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
