// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/dictitem"
	"blog-server/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DictItemUpdate is the builder for updating DictItem entities.
type DictItemUpdate struct {
	config
	hooks    []Hook
	mutation *DictItemMutation
}

// Where appends a list predicates to the DictItemUpdate builder.
func (_u *DictItemUpdate) Where(ps ...predicate.DictItem) *DictItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDictType sets the "dictType" field.
func (_u *DictItemUpdate) SetDictType(v string) *DictItemUpdate {
	_u.mutation.SetDictType(v)
	return _u
}

// SetNillableDictType sets the "dictType" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableDictType(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetDictType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *DictItemUpdate) SetValue(v int) *DictItemUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableValue(v *int) *DictItemUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *DictItemUpdate) AddValue(v int) *DictItemUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *DictItemUpdate) SetLabel(v string) *DictItemUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableLabel(v *string) *DictItemUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DictItemUpdate) SetEnabled(v bool) *DictItemUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableEnabled(v *bool) *DictItemUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *DictItemUpdate) SetSort(v int) *DictItemUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DictItemUpdate) SetNillableSort(v *int) *DictItemUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DictItemUpdate) AddSort(v int) *DictItemUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DictItemUpdate) SetUpdatedAt(v time.Time) *DictItemUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DictItemMutation object of the builder.
func (_u *DictItemUpdate) Mutation() *DictItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictItemUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictItemUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictItemUpdate) check() error {
	if v, ok := _u.mutation.DictType(); ok {
		if err := dictitem.DictTypeValidator(v); err != nil {
			return &ValidationError{Name: "dictType", err: fmt.Errorf(`ent: validator failed for field "DictItem.dictType": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := dictitem.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DictItem.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := dictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "DictItem.label": %w`, err)}
		}
	}
	return nil
}

func (_u *DictItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictitem.Table, dictitem.Columns, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DictType(); ok {
		_spec.SetField(dictitem.FieldDictType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(dictitem.FieldValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(dictitem.FieldValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(dictitem.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dictitem.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(dictitem.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(dictitem.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictItemUpdateOne is the builder for updating a single DictItem entity.
type DictItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictItemMutation
}

// SetDictType sets the "dictType" field.
func (_u *DictItemUpdateOne) SetDictType(v string) *DictItemUpdateOne {
	_u.mutation.SetDictType(v)
	return _u
}

// SetNillableDictType sets the "dictType" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableDictType(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetDictType(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *DictItemUpdateOne) SetValue(v int) *DictItemUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableValue(v *int) *DictItemUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *DictItemUpdateOne) AddValue(v int) *DictItemUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *DictItemUpdateOne) SetLabel(v string) *DictItemUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableLabel(v *string) *DictItemUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *DictItemUpdateOne) SetEnabled(v bool) *DictItemUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableEnabled(v *bool) *DictItemUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *DictItemUpdateOne) SetSort(v int) *DictItemUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DictItemUpdateOne) SetNillableSort(v *int) *DictItemUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DictItemUpdateOne) AddSort(v int) *DictItemUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *DictItemUpdateOne) SetUpdatedAt(v time.Time) *DictItemUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DictItemMutation object of the builder.
func (_u *DictItemUpdateOne) Mutation() *DictItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictItemUpdate builder.
func (_u *DictItemUpdateOne) Where(ps ...predicate.DictItem) *DictItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictItemUpdateOne) Select(field string, fields ...string) *DictItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictItem entity.
func (_u *DictItemUpdateOne) Save(ctx context.Context) (*DictItem, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictItemUpdateOne) SaveX(ctx context.Context) *DictItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictItemUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dictitem.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DictItemUpdateOne) check() error {
	if v, ok := _u.mutation.DictType(); ok {
		if err := dictitem.DictTypeValidator(v); err != nil {
			return &ValidationError{Name: "dictType", err: fmt.Errorf(`ent: validator failed for field "DictItem.dictType": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Value(); ok {
		if err := dictitem.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DictItem.value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Label(); ok {
		if err := dictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "DictItem.label": %w`, err)}
		}
	}
	return nil
}

func (_u *DictItemUpdateOne) sqlSave(ctx context.Context) (_node *DictItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dictitem.Table, dictitem.Columns, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictitem.FieldID)
		for _, f := range fields {
			if !dictitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DictType(); ok {
		_spec.SetField(dictitem.FieldDictType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(dictitem.FieldValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(dictitem.FieldValue, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(dictitem.FieldLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(dictitem.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(dictitem.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(dictitem.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DictItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
