// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/game"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// SteamAppId holds the value of the "steamAppId" field.
	SteamAppId uint32 `json:"steamAppId,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// NameZh holds the value of the "nameZh" field.
	NameZh *string `json:"nameZh,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover string `json:"cover,omitempty"`
	// Genres holds the value of the "genres" field.
	Genres []string `json:"genres,omitempty"`
	// PlaytimeMinutes holds the value of the "playtimeMinutes" field.
	PlaytimeMinutes uint32 `json:"playtimeMinutes,omitempty"`
	// Playtime2WeeksMinutes holds the value of the "playtime2WeeksMinutes" field.
	Playtime2WeeksMinutes uint32 `json:"playtime2WeeksMinutes,omitempty"`
	// LastPlayedAt holds the value of the "lastPlayedAt" field.
	LastPlayedAt *time.Time `json:"lastPlayedAt,omitempty"`
	// AchievementUnlocked holds the value of the "achievementUnlocked" field.
	AchievementUnlocked *uint32 `json:"achievementUnlocked,omitempty"`
	// AchievementTotal holds the value of the "achievementTotal" field.
	AchievementTotal *uint32 `json:"achievementTotal,omitempty"`
	// ProgressPercent holds the value of the "progressPercent" field.
	ProgressPercent *uint8 `json:"progressPercent,omitempty"`
	// ProgressSource holds the value of the "progressSource" field.
	ProgressSource string `json:"progressSource,omitempty"`
	// PlayStatus holds the value of the "playStatus" field.
	PlayStatus string `json:"playStatus,omitempty"`
	// IsVisible holds the value of the "isVisible" field.
	IsVisible bool `json:"isVisible,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort,omitempty"`
	// SyncedAt holds the value of the "syncedAt" field.
	SyncedAt *time.Time `json:"syncedAt,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt    time.Time `json:"updatedAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldGenres:
			values[i] = new([]byte)
		case game.FieldIsVisible:
			values[i] = new(sql.NullBool)
		case game.FieldID, game.FieldSteamAppId, game.FieldPlaytimeMinutes, game.FieldPlaytime2WeeksMinutes, game.FieldAchievementUnlocked, game.FieldAchievementTotal, game.FieldProgressPercent, game.FieldSort:
			values[i] = new(sql.NullInt64)
		case game.FieldName, game.FieldNameZh, game.FieldCover, game.FieldProgressSource, game.FieldPlayStatus:
			values[i] = new(sql.NullString)
		case game.FieldLastPlayedAt, game.FieldSyncedAt, game.FieldCreatedAt, game.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case game.FieldSteamAppId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field steamAppId", values[i])
			} else if value.Valid {
				_m.SteamAppId = uint32(value.Int64)
			}
		case game.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case game.FieldNameZh:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nameZh", values[i])
			} else if value.Valid {
				_m.NameZh = new(string)
				*_m.NameZh = value.String
			}
		case game.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				_m.Cover = value.String
			}
		case game.FieldGenres:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field genres", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Genres); err != nil {
					return fmt.Errorf("unmarshal field genres: %w", err)
				}
			}
		case game.FieldPlaytimeMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field playtimeMinutes", values[i])
			} else if value.Valid {
				_m.PlaytimeMinutes = uint32(value.Int64)
			}
		case game.FieldPlaytime2WeeksMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field playtime2WeeksMinutes", values[i])
			} else if value.Valid {
				_m.Playtime2WeeksMinutes = uint32(value.Int64)
			}
		case game.FieldLastPlayedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lastPlayedAt", values[i])
			} else if value.Valid {
				_m.LastPlayedAt = new(time.Time)
				*_m.LastPlayedAt = value.Time
			}
		case game.FieldAchievementUnlocked:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field achievementUnlocked", values[i])
			} else if value.Valid {
				_m.AchievementUnlocked = new(uint32)
				*_m.AchievementUnlocked = uint32(value.Int64)
			}
		case game.FieldAchievementTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field achievementTotal", values[i])
			} else if value.Valid {
				_m.AchievementTotal = new(uint32)
				*_m.AchievementTotal = uint32(value.Int64)
			}
		case game.FieldProgressPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progressPercent", values[i])
			} else if value.Valid {
				_m.ProgressPercent = new(uint8)
				*_m.ProgressPercent = uint8(value.Int64)
			}
		case game.FieldProgressSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field progressSource", values[i])
			} else if value.Valid {
				_m.ProgressSource = value.String
			}
		case game.FieldPlayStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field playStatus", values[i])
			} else if value.Valid {
				_m.PlayStatus = value.String
			}
		case game.FieldIsVisible:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field isVisible", values[i])
			} else if value.Valid {
				_m.IsVisible = value.Bool
			}
		case game.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = int(value.Int64)
			}
		case game.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field syncedAt", values[i])
			} else if value.Valid {
				_m.SyncedAt = new(time.Time)
				*_m.SyncedAt = value.Time
			}
		case game.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case game.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("steamAppId=")
	builder.WriteString(fmt.Sprintf("%v", _m.SteamAppId))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.NameZh; v != nil {
		builder.WriteString("nameZh=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("cover=")
	builder.WriteString(_m.Cover)
	builder.WriteString(", ")
	builder.WriteString("genres=")
	builder.WriteString(fmt.Sprintf("%v", _m.Genres))
	builder.WriteString(", ")
	builder.WriteString("playtimeMinutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaytimeMinutes))
	builder.WriteString(", ")
	builder.WriteString("playtime2WeeksMinutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Playtime2WeeksMinutes))
	builder.WriteString(", ")
	if v := _m.LastPlayedAt; v != nil {
		builder.WriteString("lastPlayedAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AchievementUnlocked; v != nil {
		builder.WriteString("achievementUnlocked=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AchievementTotal; v != nil {
		builder.WriteString("achievementTotal=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProgressPercent; v != nil {
		builder.WriteString("progressPercent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("progressSource=")
	builder.WriteString(_m.ProgressSource)
	builder.WriteString(", ")
	builder.WriteString("playStatus=")
	builder.WriteString(_m.PlayStatus)
	builder.WriteString(", ")
	builder.WriteString("isVisible=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsVisible))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	if v := _m.SyncedAt; v != nil {
		builder.WriteString("syncedAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Games is a parsable slice of Game.
type Games []*Game
