// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/gameplaytimesnapshot"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GamePlaytimeSnapshot is the model entity for the GamePlaytimeSnapshot schema.
type GamePlaytimeSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// SteamAppId holds the value of the "steamAppId" field.
	SteamAppId uint32 `json:"steamAppId,omitempty"`
	// PlaytimeMinutes holds the value of the "playtimeMinutes" field.
	PlaytimeMinutes uint32 `json:"playtimeMinutes,omitempty"`
	// SnapshotAt holds the value of the "snapshotAt" field.
	SnapshotAt   time.Time `json:"snapshotAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GamePlaytimeSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gameplaytimesnapshot.FieldID, gameplaytimesnapshot.FieldSteamAppId, gameplaytimesnapshot.FieldPlaytimeMinutes:
			values[i] = new(sql.NullInt64)
		case gameplaytimesnapshot.FieldSnapshotAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GamePlaytimeSnapshot fields.
func (_m *GamePlaytimeSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gameplaytimesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case gameplaytimesnapshot.FieldSteamAppId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field steamAppId", values[i])
			} else if value.Valid {
				_m.SteamAppId = uint32(value.Int64)
			}
		case gameplaytimesnapshot.FieldPlaytimeMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field playtimeMinutes", values[i])
			} else if value.Valid {
				_m.PlaytimeMinutes = uint32(value.Int64)
			}
		case gameplaytimesnapshot.FieldSnapshotAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field snapshotAt", values[i])
			} else if value.Valid {
				_m.SnapshotAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GamePlaytimeSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *GamePlaytimeSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GamePlaytimeSnapshot.
// Note that you need to call GamePlaytimeSnapshot.Unwrap() before calling this method if this GamePlaytimeSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GamePlaytimeSnapshot) Update() *GamePlaytimeSnapshotUpdateOne {
	return NewGamePlaytimeSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GamePlaytimeSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GamePlaytimeSnapshot) Unwrap() *GamePlaytimeSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GamePlaytimeSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GamePlaytimeSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("GamePlaytimeSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("steamAppId=")
	builder.WriteString(fmt.Sprintf("%v", _m.SteamAppId))
	builder.WriteString(", ")
	builder.WriteString("playtimeMinutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlaytimeMinutes))
	builder.WriteString(", ")
	builder.WriteString("snapshotAt=")
	builder.WriteString(_m.SnapshotAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GamePlaytimeSnapshots is a parsable slice of GamePlaytimeSnapshot.
type GamePlaytimeSnapshots []*GamePlaytimeSnapshot
