// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/game"
	"blog-server/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// GameUpdate is the builder for updating Game entities.
type GameUpdate struct {
	config
	hooks    []Hook
	mutation *GameMutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdate) Where(ps ...predicate.Game) *GameUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSteamAppId sets the "steamAppId" field.
func (_u *GameUpdate) SetSteamAppId(v uint32) *GameUpdate {
	_u.mutation.ResetSteamAppId()
	_u.mutation.SetSteamAppId(v)
	return _u
}

// SetNillableSteamAppId sets the "steamAppId" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSteamAppId(v *uint32) *GameUpdate {
	if v != nil {
		_u.SetSteamAppId(*v)
	}
	return _u
}

// AddSteamAppId adds value to the "steamAppId" field.
func (_u *GameUpdate) AddSteamAppId(v int32) *GameUpdate {
	_u.mutation.AddSteamAppId(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GameUpdate) SetName(v string) *GameUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdate) SetNillableName(v *string) *GameUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameZh sets the "nameZh" field.
func (_u *GameUpdate) SetNameZh(v string) *GameUpdate {
	_u.mutation.SetNameZh(v)
	return _u
}

// SetNillableNameZh sets the "nameZh" field if the given value is not nil.
func (_u *GameUpdate) SetNillableNameZh(v *string) *GameUpdate {
	if v != nil {
		_u.SetNameZh(*v)
	}
	return _u
}

// ClearNameZh clears the value of the "nameZh" field.
func (_u *GameUpdate) ClearNameZh() *GameUpdate {
	_u.mutation.ClearNameZh()
	return _u
}

// SetCover sets the "cover" field.
func (_u *GameUpdate) SetCover(v string) *GameUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *GameUpdate) SetNillableCover(v *string) *GameUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *GameUpdate) ClearCover() *GameUpdate {
	_u.mutation.ClearCover()
	return _u
}

// SetGenres sets the "genres" field.
func (_u *GameUpdate) SetGenres(v []string) *GameUpdate {
	_u.mutation.SetGenres(v)
	return _u
}

// AppendGenres appends value to the "genres" field.
func (_u *GameUpdate) AppendGenres(v []string) *GameUpdate {
	_u.mutation.AppendGenres(v)
	return _u
}

// SetPlaytimeMinutes sets the "playtimeMinutes" field.
func (_u *GameUpdate) SetPlaytimeMinutes(v uint32) *GameUpdate {
	_u.mutation.ResetPlaytimeMinutes()
	_u.mutation.SetPlaytimeMinutes(v)
	return _u
}

// SetNillablePlaytimeMinutes sets the "playtimeMinutes" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlaytimeMinutes(v *uint32) *GameUpdate {
	if v != nil {
		_u.SetPlaytimeMinutes(*v)
	}
	return _u
}

// AddPlaytimeMinutes adds value to the "playtimeMinutes" field.
func (_u *GameUpdate) AddPlaytimeMinutes(v int32) *GameUpdate {
	_u.mutation.AddPlaytimeMinutes(v)
	return _u
}

// SetPlaytime2WeeksMinutes sets the "playtime2WeeksMinutes" field.
func (_u *GameUpdate) SetPlaytime2WeeksMinutes(v uint32) *GameUpdate {
	_u.mutation.ResetPlaytime2WeeksMinutes()
	_u.mutation.SetPlaytime2WeeksMinutes(v)
	return _u
}

// SetNillablePlaytime2WeeksMinutes sets the "playtime2WeeksMinutes" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlaytime2WeeksMinutes(v *uint32) *GameUpdate {
	if v != nil {
		_u.SetPlaytime2WeeksMinutes(*v)
	}
	return _u
}

// AddPlaytime2WeeksMinutes adds value to the "playtime2WeeksMinutes" field.
func (_u *GameUpdate) AddPlaytime2WeeksMinutes(v int32) *GameUpdate {
	_u.mutation.AddPlaytime2WeeksMinutes(v)
	return _u
}

// SetLastPlayedAt sets the "lastPlayedAt" field.
func (_u *GameUpdate) SetLastPlayedAt(v time.Time) *GameUpdate {
	_u.mutation.SetLastPlayedAt(v)
	return _u
}

// SetNillableLastPlayedAt sets the "lastPlayedAt" field if the given value is not nil.
func (_u *GameUpdate) SetNillableLastPlayedAt(v *time.Time) *GameUpdate {
	if v != nil {
		_u.SetLastPlayedAt(*v)
	}
	return _u
}

// ClearLastPlayedAt clears the value of the "lastPlayedAt" field.
func (_u *GameUpdate) ClearLastPlayedAt() *GameUpdate {
	_u.mutation.ClearLastPlayedAt()
	return _u
}

// SetAchievementUnlocked sets the "achievementUnlocked" field.
func (_u *GameUpdate) SetAchievementUnlocked(v uint32) *GameUpdate {
	_u.mutation.ResetAchievementUnlocked()
	_u.mutation.SetAchievementUnlocked(v)
	return _u
}

// SetNillableAchievementUnlocked sets the "achievementUnlocked" field if the given value is not nil.
func (_u *GameUpdate) SetNillableAchievementUnlocked(v *uint32) *GameUpdate {
	if v != nil {
		_u.SetAchievementUnlocked(*v)
	}
	return _u
}

// AddAchievementUnlocked adds value to the "achievementUnlocked" field.
func (_u *GameUpdate) AddAchievementUnlocked(v int32) *GameUpdate {
	_u.mutation.AddAchievementUnlocked(v)
	return _u
}

// ClearAchievementUnlocked clears the value of the "achievementUnlocked" field.
func (_u *GameUpdate) ClearAchievementUnlocked() *GameUpdate {
	_u.mutation.ClearAchievementUnlocked()
	return _u
}

// SetAchievementTotal sets the "achievementTotal" field.
func (_u *GameUpdate) SetAchievementTotal(v uint32) *GameUpdate {
	_u.mutation.ResetAchievementTotal()
	_u.mutation.SetAchievementTotal(v)
	return _u
}

// SetNillableAchievementTotal sets the "achievementTotal" field if the given value is not nil.
func (_u *GameUpdate) SetNillableAchievementTotal(v *uint32) *GameUpdate {
	if v != nil {
		_u.SetAchievementTotal(*v)
	}
	return _u
}

// AddAchievementTotal adds value to the "achievementTotal" field.
func (_u *GameUpdate) AddAchievementTotal(v int32) *GameUpdate {
	_u.mutation.AddAchievementTotal(v)
	return _u
}

// ClearAchievementTotal clears the value of the "achievementTotal" field.
func (_u *GameUpdate) ClearAchievementTotal() *GameUpdate {
	_u.mutation.ClearAchievementTotal()
	return _u
}

// SetProgressPercent sets the "progressPercent" field.
func (_u *GameUpdate) SetProgressPercent(v uint8) *GameUpdate {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progressPercent" field if the given value is not nil.
func (_u *GameUpdate) SetNillableProgressPercent(v *uint8) *GameUpdate {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progressPercent" field.
func (_u *GameUpdate) AddProgressPercent(v int8) *GameUpdate {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// ClearProgressPercent clears the value of the "progressPercent" field.
func (_u *GameUpdate) ClearProgressPercent() *GameUpdate {
	_u.mutation.ClearProgressPercent()
	return _u
}

// SetProgressSource sets the "progressSource" field.
func (_u *GameUpdate) SetProgressSource(v string) *GameUpdate {
	_u.mutation.SetProgressSource(v)
	return _u
}

// SetNillableProgressSource sets the "progressSource" field if the given value is not nil.
func (_u *GameUpdate) SetNillableProgressSource(v *string) *GameUpdate {
	if v != nil {
		_u.SetProgressSource(*v)
	}
	return _u
}

// SetPlayStatus sets the "playStatus" field.
func (_u *GameUpdate) SetPlayStatus(v string) *GameUpdate {
	_u.mutation.SetPlayStatus(v)
	return _u
}

// SetNillablePlayStatus sets the "playStatus" field if the given value is not nil.
func (_u *GameUpdate) SetNillablePlayStatus(v *string) *GameUpdate {
	if v != nil {
		_u.SetPlayStatus(*v)
	}
	return _u
}

// SetIsVisible sets the "isVisible" field.
func (_u *GameUpdate) SetIsVisible(v bool) *GameUpdate {
	_u.mutation.SetIsVisible(v)
	return _u
}

// SetNillableIsVisible sets the "isVisible" field if the given value is not nil.
func (_u *GameUpdate) SetNillableIsVisible(v *bool) *GameUpdate {
	if v != nil {
		_u.SetIsVisible(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *GameUpdate) SetSort(v int) *GameUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSort(v *int) *GameUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *GameUpdate) AddSort(v int) *GameUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetSyncedAt sets the "syncedAt" field.
func (_u *GameUpdate) SetSyncedAt(v time.Time) *GameUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "syncedAt" field if the given value is not nil.
func (_u *GameUpdate) SetNillableSyncedAt(v *time.Time) *GameUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "syncedAt" field.
func (_u *GameUpdate) ClearSyncedAt() *GameUpdate {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *GameUpdate) SetUpdatedAt(v time.Time) *GameUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdate) Mutation() *GameMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := game.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Game.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameZh(); ok {
		if err := game.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "nameZh", err: fmt.Errorf(`ent: validator failed for field "Game.nameZh": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cover(); ok {
		if err := game.CoverValidator(v); err != nil {
			return &ValidationError{Name: "cover", err: fmt.Errorf(`ent: validator failed for field "Game.cover": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressSource(); ok {
		if err := game.ProgressSourceValidator(v); err != nil {
			return &ValidationError{Name: "progressSource", err: fmt.Errorf(`ent: validator failed for field "Game.progressSource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayStatus(); ok {
		if err := game.PlayStatusValidator(v); err != nil {
			return &ValidationError{Name: "playStatus", err: fmt.Errorf(`ent: validator failed for field "Game.playStatus": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SteamAppId(); ok {
		_spec.SetField(game.FieldSteamAppId, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSteamAppId(); ok {
		_spec.AddField(game.FieldSteamAppId, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameZh(); ok {
		_spec.SetField(game.FieldNameZh, field.TypeString, value)
	}
	if _u.mutation.NameZhCleared() {
		_spec.ClearField(game.FieldNameZh, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(game.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(game.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Genres(); ok {
		_spec.SetField(game.FieldGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldGenres, value)
		})
	}
	if value, ok := _u.mutation.PlaytimeMinutes(); ok {
		_spec.SetField(game.FieldPlaytimeMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPlaytimeMinutes(); ok {
		_spec.AddField(game.FieldPlaytimeMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Playtime2WeeksMinutes(); ok {
		_spec.SetField(game.FieldPlaytime2WeeksMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPlaytime2WeeksMinutes(); ok {
		_spec.AddField(game.FieldPlaytime2WeeksMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.LastPlayedAt(); ok {
		_spec.SetField(game.FieldLastPlayedAt, field.TypeTime, value)
	}
	if _u.mutation.LastPlayedAtCleared() {
		_spec.ClearField(game.FieldLastPlayedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AchievementUnlocked(); ok {
		_spec.SetField(game.FieldAchievementUnlocked, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAchievementUnlocked(); ok {
		_spec.AddField(game.FieldAchievementUnlocked, field.TypeUint32, value)
	}
	if _u.mutation.AchievementUnlockedCleared() {
		_spec.ClearField(game.FieldAchievementUnlocked, field.TypeUint32)
	}
	if value, ok := _u.mutation.AchievementTotal(); ok {
		_spec.SetField(game.FieldAchievementTotal, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAchievementTotal(); ok {
		_spec.AddField(game.FieldAchievementTotal, field.TypeUint32, value)
	}
	if _u.mutation.AchievementTotalCleared() {
		_spec.ClearField(game.FieldAchievementTotal, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(game.FieldProgressPercent, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(game.FieldProgressPercent, field.TypeUint8, value)
	}
	if _u.mutation.ProgressPercentCleared() {
		_spec.ClearField(game.FieldProgressPercent, field.TypeUint8)
	}
	if value, ok := _u.mutation.ProgressSource(); ok {
		_spec.SetField(game.FieldProgressSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayStatus(); ok {
		_spec.SetField(game.FieldPlayStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsVisible(); ok {
		_spec.SetField(game.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(game.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(game.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(game.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(game.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameUpdateOne is the builder for updating a single Game entity.
type GameUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMutation
}

// SetSteamAppId sets the "steamAppId" field.
func (_u *GameUpdateOne) SetSteamAppId(v uint32) *GameUpdateOne {
	_u.mutation.ResetSteamAppId()
	_u.mutation.SetSteamAppId(v)
	return _u
}

// SetNillableSteamAppId sets the "steamAppId" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSteamAppId(v *uint32) *GameUpdateOne {
	if v != nil {
		_u.SetSteamAppId(*v)
	}
	return _u
}

// AddSteamAppId adds value to the "steamAppId" field.
func (_u *GameUpdateOne) AddSteamAppId(v int32) *GameUpdateOne {
	_u.mutation.AddSteamAppId(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GameUpdateOne) SetName(v string) *GameUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableName(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNameZh sets the "nameZh" field.
func (_u *GameUpdateOne) SetNameZh(v string) *GameUpdateOne {
	_u.mutation.SetNameZh(v)
	return _u
}

// SetNillableNameZh sets the "nameZh" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableNameZh(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetNameZh(*v)
	}
	return _u
}

// ClearNameZh clears the value of the "nameZh" field.
func (_u *GameUpdateOne) ClearNameZh() *GameUpdateOne {
	_u.mutation.ClearNameZh()
	return _u
}

// SetCover sets the "cover" field.
func (_u *GameUpdateOne) SetCover(v string) *GameUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableCover(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// ClearCover clears the value of the "cover" field.
func (_u *GameUpdateOne) ClearCover() *GameUpdateOne {
	_u.mutation.ClearCover()
	return _u
}

// SetGenres sets the "genres" field.
func (_u *GameUpdateOne) SetGenres(v []string) *GameUpdateOne {
	_u.mutation.SetGenres(v)
	return _u
}

// AppendGenres appends value to the "genres" field.
func (_u *GameUpdateOne) AppendGenres(v []string) *GameUpdateOne {
	_u.mutation.AppendGenres(v)
	return _u
}

// SetPlaytimeMinutes sets the "playtimeMinutes" field.
func (_u *GameUpdateOne) SetPlaytimeMinutes(v uint32) *GameUpdateOne {
	_u.mutation.ResetPlaytimeMinutes()
	_u.mutation.SetPlaytimeMinutes(v)
	return _u
}

// SetNillablePlaytimeMinutes sets the "playtimeMinutes" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlaytimeMinutes(v *uint32) *GameUpdateOne {
	if v != nil {
		_u.SetPlaytimeMinutes(*v)
	}
	return _u
}

// AddPlaytimeMinutes adds value to the "playtimeMinutes" field.
func (_u *GameUpdateOne) AddPlaytimeMinutes(v int32) *GameUpdateOne {
	_u.mutation.AddPlaytimeMinutes(v)
	return _u
}

// SetPlaytime2WeeksMinutes sets the "playtime2WeeksMinutes" field.
func (_u *GameUpdateOne) SetPlaytime2WeeksMinutes(v uint32) *GameUpdateOne {
	_u.mutation.ResetPlaytime2WeeksMinutes()
	_u.mutation.SetPlaytime2WeeksMinutes(v)
	return _u
}

// SetNillablePlaytime2WeeksMinutes sets the "playtime2WeeksMinutes" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlaytime2WeeksMinutes(v *uint32) *GameUpdateOne {
	if v != nil {
		_u.SetPlaytime2WeeksMinutes(*v)
	}
	return _u
}

// AddPlaytime2WeeksMinutes adds value to the "playtime2WeeksMinutes" field.
func (_u *GameUpdateOne) AddPlaytime2WeeksMinutes(v int32) *GameUpdateOne {
	_u.mutation.AddPlaytime2WeeksMinutes(v)
	return _u
}

// SetLastPlayedAt sets the "lastPlayedAt" field.
func (_u *GameUpdateOne) SetLastPlayedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetLastPlayedAt(v)
	return _u
}

// SetNillableLastPlayedAt sets the "lastPlayedAt" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableLastPlayedAt(v *time.Time) *GameUpdateOne {
	if v != nil {
		_u.SetLastPlayedAt(*v)
	}
	return _u
}

// ClearLastPlayedAt clears the value of the "lastPlayedAt" field.
func (_u *GameUpdateOne) ClearLastPlayedAt() *GameUpdateOne {
	_u.mutation.ClearLastPlayedAt()
	return _u
}

// SetAchievementUnlocked sets the "achievementUnlocked" field.
func (_u *GameUpdateOne) SetAchievementUnlocked(v uint32) *GameUpdateOne {
	_u.mutation.ResetAchievementUnlocked()
	_u.mutation.SetAchievementUnlocked(v)
	return _u
}

// SetNillableAchievementUnlocked sets the "achievementUnlocked" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableAchievementUnlocked(v *uint32) *GameUpdateOne {
	if v != nil {
		_u.SetAchievementUnlocked(*v)
	}
	return _u
}

// AddAchievementUnlocked adds value to the "achievementUnlocked" field.
func (_u *GameUpdateOne) AddAchievementUnlocked(v int32) *GameUpdateOne {
	_u.mutation.AddAchievementUnlocked(v)
	return _u
}

// ClearAchievementUnlocked clears the value of the "achievementUnlocked" field.
func (_u *GameUpdateOne) ClearAchievementUnlocked() *GameUpdateOne {
	_u.mutation.ClearAchievementUnlocked()
	return _u
}

// SetAchievementTotal sets the "achievementTotal" field.
func (_u *GameUpdateOne) SetAchievementTotal(v uint32) *GameUpdateOne {
	_u.mutation.ResetAchievementTotal()
	_u.mutation.SetAchievementTotal(v)
	return _u
}

// SetNillableAchievementTotal sets the "achievementTotal" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableAchievementTotal(v *uint32) *GameUpdateOne {
	if v != nil {
		_u.SetAchievementTotal(*v)
	}
	return _u
}

// AddAchievementTotal adds value to the "achievementTotal" field.
func (_u *GameUpdateOne) AddAchievementTotal(v int32) *GameUpdateOne {
	_u.mutation.AddAchievementTotal(v)
	return _u
}

// ClearAchievementTotal clears the value of the "achievementTotal" field.
func (_u *GameUpdateOne) ClearAchievementTotal() *GameUpdateOne {
	_u.mutation.ClearAchievementTotal()
	return _u
}

// SetProgressPercent sets the "progressPercent" field.
func (_u *GameUpdateOne) SetProgressPercent(v uint8) *GameUpdateOne {
	_u.mutation.ResetProgressPercent()
	_u.mutation.SetProgressPercent(v)
	return _u
}

// SetNillableProgressPercent sets the "progressPercent" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableProgressPercent(v *uint8) *GameUpdateOne {
	if v != nil {
		_u.SetProgressPercent(*v)
	}
	return _u
}

// AddProgressPercent adds value to the "progressPercent" field.
func (_u *GameUpdateOne) AddProgressPercent(v int8) *GameUpdateOne {
	_u.mutation.AddProgressPercent(v)
	return _u
}

// ClearProgressPercent clears the value of the "progressPercent" field.
func (_u *GameUpdateOne) ClearProgressPercent() *GameUpdateOne {
	_u.mutation.ClearProgressPercent()
	return _u
}

// SetProgressSource sets the "progressSource" field.
func (_u *GameUpdateOne) SetProgressSource(v string) *GameUpdateOne {
	_u.mutation.SetProgressSource(v)
	return _u
}

// SetNillableProgressSource sets the "progressSource" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableProgressSource(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetProgressSource(*v)
	}
	return _u
}

// SetPlayStatus sets the "playStatus" field.
func (_u *GameUpdateOne) SetPlayStatus(v string) *GameUpdateOne {
	_u.mutation.SetPlayStatus(v)
	return _u
}

// SetNillablePlayStatus sets the "playStatus" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillablePlayStatus(v *string) *GameUpdateOne {
	if v != nil {
		_u.SetPlayStatus(*v)
	}
	return _u
}

// SetIsVisible sets the "isVisible" field.
func (_u *GameUpdateOne) SetIsVisible(v bool) *GameUpdateOne {
	_u.mutation.SetIsVisible(v)
	return _u
}

// SetNillableIsVisible sets the "isVisible" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableIsVisible(v *bool) *GameUpdateOne {
	if v != nil {
		_u.SetIsVisible(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *GameUpdateOne) SetSort(v int) *GameUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSort(v *int) *GameUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *GameUpdateOne) AddSort(v int) *GameUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetSyncedAt sets the "syncedAt" field.
func (_u *GameUpdateOne) SetSyncedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "syncedAt" field if the given value is not nil.
func (_u *GameUpdateOne) SetNillableSyncedAt(v *time.Time) *GameUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// ClearSyncedAt clears the value of the "syncedAt" field.
func (_u *GameUpdateOne) ClearSyncedAt() *GameUpdateOne {
	_u.mutation.ClearSyncedAt()
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *GameUpdateOne) SetUpdatedAt(v time.Time) *GameUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMutation object of the builder.
func (_u *GameUpdateOne) Mutation() *GameMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameUpdate builder.
func (_u *GameUpdateOne) Where(ps ...predicate.Game) *GameUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameUpdateOne) Select(field string, fields ...string) *GameUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Game entity.
func (_u *GameUpdateOne) Save(ctx context.Context) (*Game, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameUpdateOne) SaveX(ctx context.Context) *Game {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := game.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := game.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Game.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameZh(); ok {
		if err := game.NameZhValidator(v); err != nil {
			return &ValidationError{Name: "nameZh", err: fmt.Errorf(`ent: validator failed for field "Game.nameZh": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cover(); ok {
		if err := game.CoverValidator(v); err != nil {
			return &ValidationError{Name: "cover", err: fmt.Errorf(`ent: validator failed for field "Game.cover": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProgressSource(); ok {
		if err := game.ProgressSourceValidator(v); err != nil {
			return &ValidationError{Name: "progressSource", err: fmt.Errorf(`ent: validator failed for field "Game.progressSource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlayStatus(); ok {
		if err := game.PlayStatusValidator(v); err != nil {
			return &ValidationError{Name: "playStatus", err: fmt.Errorf(`ent: validator failed for field "Game.playStatus": %w`, err)}
		}
	}
	return nil
}

func (_u *GameUpdateOne) sqlSave(ctx context.Context) (_node *Game, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(game.Table, game.Columns, sqlgraph.NewFieldSpec(game.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Game.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, game.FieldID)
		for _, f := range fields {
			if !game.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != game.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SteamAppId(); ok {
		_spec.SetField(game.FieldSteamAppId, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedSteamAppId(); ok {
		_spec.AddField(game.FieldSteamAppId, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(game.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameZh(); ok {
		_spec.SetField(game.FieldNameZh, field.TypeString, value)
	}
	if _u.mutation.NameZhCleared() {
		_spec.ClearField(game.FieldNameZh, field.TypeString)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(game.FieldCover, field.TypeString, value)
	}
	if _u.mutation.CoverCleared() {
		_spec.ClearField(game.FieldCover, field.TypeString)
	}
	if value, ok := _u.mutation.Genres(); ok {
		_spec.SetField(game.FieldGenres, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenres(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, game.FieldGenres, value)
		})
	}
	if value, ok := _u.mutation.PlaytimeMinutes(); ok {
		_spec.SetField(game.FieldPlaytimeMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPlaytimeMinutes(); ok {
		_spec.AddField(game.FieldPlaytimeMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Playtime2WeeksMinutes(); ok {
		_spec.SetField(game.FieldPlaytime2WeeksMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedPlaytime2WeeksMinutes(); ok {
		_spec.AddField(game.FieldPlaytime2WeeksMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.LastPlayedAt(); ok {
		_spec.SetField(game.FieldLastPlayedAt, field.TypeTime, value)
	}
	if _u.mutation.LastPlayedAtCleared() {
		_spec.ClearField(game.FieldLastPlayedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AchievementUnlocked(); ok {
		_spec.SetField(game.FieldAchievementUnlocked, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAchievementUnlocked(); ok {
		_spec.AddField(game.FieldAchievementUnlocked, field.TypeUint32, value)
	}
	if _u.mutation.AchievementUnlockedCleared() {
		_spec.ClearField(game.FieldAchievementUnlocked, field.TypeUint32)
	}
	if value, ok := _u.mutation.AchievementTotal(); ok {
		_spec.SetField(game.FieldAchievementTotal, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedAchievementTotal(); ok {
		_spec.AddField(game.FieldAchievementTotal, field.TypeUint32, value)
	}
	if _u.mutation.AchievementTotalCleared() {
		_spec.ClearField(game.FieldAchievementTotal, field.TypeUint32)
	}
	if value, ok := _u.mutation.ProgressPercent(); ok {
		_spec.SetField(game.FieldProgressPercent, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedProgressPercent(); ok {
		_spec.AddField(game.FieldProgressPercent, field.TypeUint8, value)
	}
	if _u.mutation.ProgressPercentCleared() {
		_spec.ClearField(game.FieldProgressPercent, field.TypeUint8)
	}
	if value, ok := _u.mutation.ProgressSource(); ok {
		_spec.SetField(game.FieldProgressSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayStatus(); ok {
		_spec.SetField(game.FieldPlayStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsVisible(); ok {
		_spec.SetField(game.FieldIsVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(game.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(game.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(game.FieldSyncedAt, field.TypeTime, value)
	}
	if _u.mutation.SyncedAtCleared() {
		_spec.ClearField(game.FieldSyncedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(game.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Game{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{game.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
