// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/gamemonthlystat"
	"blog-server/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameMonthlyStatUpdate is the builder for updating GameMonthlyStat entities.
type GameMonthlyStatUpdate struct {
	config
	hooks    []Hook
	mutation *GameMonthlyStatMutation
}

// Where appends a list predicates to the GameMonthlyStatUpdate builder.
func (_u *GameMonthlyStatUpdate) Where(ps ...predicate.GameMonthlyStat) *GameMonthlyStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetYearMonth sets the "yearMonth" field.
func (_u *GameMonthlyStatUpdate) SetYearMonth(v string) *GameMonthlyStatUpdate {
	_u.mutation.SetYearMonth(v)
	return _u
}

// SetNillableYearMonth sets the "yearMonth" field if the given value is not nil.
func (_u *GameMonthlyStatUpdate) SetNillableYearMonth(v *string) *GameMonthlyStatUpdate {
	if v != nil {
		_u.SetYearMonth(*v)
	}
	return _u
}

// SetTotalMinutes sets the "totalMinutes" field.
func (_u *GameMonthlyStatUpdate) SetTotalMinutes(v uint32) *GameMonthlyStatUpdate {
	_u.mutation.ResetTotalMinutes()
	_u.mutation.SetTotalMinutes(v)
	return _u
}

// SetNillableTotalMinutes sets the "totalMinutes" field if the given value is not nil.
func (_u *GameMonthlyStatUpdate) SetNillableTotalMinutes(v *uint32) *GameMonthlyStatUpdate {
	if v != nil {
		_u.SetTotalMinutes(*v)
	}
	return _u
}

// AddTotalMinutes adds value to the "totalMinutes" field.
func (_u *GameMonthlyStatUpdate) AddTotalMinutes(v int32) *GameMonthlyStatUpdate {
	_u.mutation.AddTotalMinutes(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *GameMonthlyStatUpdate) SetUpdatedAt(v time.Time) *GameMonthlyStatUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMonthlyStatMutation object of the builder.
func (_u *GameMonthlyStatUpdate) Mutation() *GameMonthlyStatMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameMonthlyStatUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameMonthlyStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameMonthlyStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameMonthlyStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameMonthlyStatUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gamemonthlystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameMonthlyStatUpdate) check() error {
	if v, ok := _u.mutation.YearMonth(); ok {
		if err := gamemonthlystat.YearMonthValidator(v); err != nil {
			return &ValidationError{Name: "yearMonth", err: fmt.Errorf(`ent: validator failed for field "GameMonthlyStat.yearMonth": %w`, err)}
		}
	}
	return nil
}

func (_u *GameMonthlyStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamemonthlystat.Table, gamemonthlystat.Columns, sqlgraph.NewFieldSpec(gamemonthlystat.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.YearMonth(); ok {
		_spec.SetField(gamemonthlystat.FieldYearMonth, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalMinutes(); ok {
		_spec.SetField(gamemonthlystat.FieldTotalMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalMinutes(); ok {
		_spec.AddField(gamemonthlystat.FieldTotalMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gamemonthlystat.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamemonthlystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameMonthlyStatUpdateOne is the builder for updating a single GameMonthlyStat entity.
type GameMonthlyStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameMonthlyStatMutation
}

// SetYearMonth sets the "yearMonth" field.
func (_u *GameMonthlyStatUpdateOne) SetYearMonth(v string) *GameMonthlyStatUpdateOne {
	_u.mutation.SetYearMonth(v)
	return _u
}

// SetNillableYearMonth sets the "yearMonth" field if the given value is not nil.
func (_u *GameMonthlyStatUpdateOne) SetNillableYearMonth(v *string) *GameMonthlyStatUpdateOne {
	if v != nil {
		_u.SetYearMonth(*v)
	}
	return _u
}

// SetTotalMinutes sets the "totalMinutes" field.
func (_u *GameMonthlyStatUpdateOne) SetTotalMinutes(v uint32) *GameMonthlyStatUpdateOne {
	_u.mutation.ResetTotalMinutes()
	_u.mutation.SetTotalMinutes(v)
	return _u
}

// SetNillableTotalMinutes sets the "totalMinutes" field if the given value is not nil.
func (_u *GameMonthlyStatUpdateOne) SetNillableTotalMinutes(v *uint32) *GameMonthlyStatUpdateOne {
	if v != nil {
		_u.SetTotalMinutes(*v)
	}
	return _u
}

// AddTotalMinutes adds value to the "totalMinutes" field.
func (_u *GameMonthlyStatUpdateOne) AddTotalMinutes(v int32) *GameMonthlyStatUpdateOne {
	_u.mutation.AddTotalMinutes(v)
	return _u
}

// SetUpdatedAt sets the "updatedAt" field.
func (_u *GameMonthlyStatUpdateOne) SetUpdatedAt(v time.Time) *GameMonthlyStatUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GameMonthlyStatMutation object of the builder.
func (_u *GameMonthlyStatUpdateOne) Mutation() *GameMonthlyStatMutation {
	return _u.mutation
}

// Where appends a list predicates to the GameMonthlyStatUpdate builder.
func (_u *GameMonthlyStatUpdateOne) Where(ps ...predicate.GameMonthlyStat) *GameMonthlyStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameMonthlyStatUpdateOne) Select(field string, fields ...string) *GameMonthlyStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameMonthlyStat entity.
func (_u *GameMonthlyStatUpdateOne) Save(ctx context.Context) (*GameMonthlyStat, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameMonthlyStatUpdateOne) SaveX(ctx context.Context) *GameMonthlyStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameMonthlyStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameMonthlyStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GameMonthlyStatUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := gamemonthlystat.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameMonthlyStatUpdateOne) check() error {
	if v, ok := _u.mutation.YearMonth(); ok {
		if err := gamemonthlystat.YearMonthValidator(v); err != nil {
			return &ValidationError{Name: "yearMonth", err: fmt.Errorf(`ent: validator failed for field "GameMonthlyStat.yearMonth": %w`, err)}
		}
	}
	return nil
}

func (_u *GameMonthlyStatUpdateOne) sqlSave(ctx context.Context) (_node *GameMonthlyStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamemonthlystat.Table, gamemonthlystat.Columns, sqlgraph.NewFieldSpec(gamemonthlystat.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameMonthlyStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamemonthlystat.FieldID)
		for _, f := range fields {
			if !gamemonthlystat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gamemonthlystat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.YearMonth(); ok {
		_spec.SetField(gamemonthlystat.FieldYearMonth, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalMinutes(); ok {
		_spec.SetField(gamemonthlystat.FieldTotalMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalMinutes(); ok {
		_spec.AddField(gamemonthlystat.FieldTotalMinutes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(gamemonthlystat.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GameMonthlyStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamemonthlystat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
