// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/operationlog"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OperationLog is the model entity for the OperationLog schema.
type OperationLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId uint64 `json:"userId,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// ActionValue holds the value of the "actionValue" field.
	ActionValue int `json:"actionValue,omitempty"`
	// ActionLabel holds the value of the "actionLabel" field.
	ActionLabel string `json:"actionLabel,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// UserAgent holds the value of the "userAgent" field.
	UserAgent string `json:"userAgent,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt    time.Time `json:"createdAt,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OperationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldID, operationlog.FieldUserId, operationlog.FieldActionValue:
			values[i] = new(sql.NullInt64)
		case operationlog.FieldUsername, operationlog.FieldActionLabel, operationlog.FieldIP, operationlog.FieldRegion, operationlog.FieldUserAgent:
			values[i] = new(sql.NullString)
		case operationlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OperationLog fields.
func (_m *OperationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case operationlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case operationlog.FieldUserId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				_m.UserId = uint64(value.Int64)
			}
		case operationlog.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case operationlog.FieldActionValue:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actionValue", values[i])
			} else if value.Valid {
				_m.ActionValue = int(value.Int64)
			}
		case operationlog.FieldActionLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actionLabel", values[i])
			} else if value.Valid {
				_m.ActionLabel = value.String
			}
		case operationlog.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case operationlog.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case operationlog.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userAgent", values[i])
			} else if value.Valid {
				_m.UserAgent = value.String
			}
		case operationlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OperationLog.
// This includes values selected through modifiers, order, etc.
func (_m *OperationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OperationLog.
// Note that you need to call OperationLog.Unwrap() before calling this method if this OperationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OperationLog) Update() *OperationLogUpdateOne {
	return NewOperationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OperationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OperationLog) Unwrap() *OperationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OperationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OperationLog) String() string {
	var builder strings.Builder
	builder.WriteString("OperationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("userId=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserId))
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("actionValue=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActionValue))
	builder.WriteString(", ")
	builder.WriteString("actionLabel=")
	builder.WriteString(_m.ActionLabel)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("userAgent=")
	builder.WriteString(_m.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OperationLogs is a parsable slice of OperationLog.
type OperationLogs []*OperationLog
