// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/post"
	"blog-server/internal/ent/posttag"
	"blog-server/internal/ent/tag"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PostTag is the model entity for the PostTag schema.
type PostTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// PostId holds the value of the "postId" field.
	PostId uint64 `json:"postId,omitempty"`
	// TagId holds the value of the "tagId" field.
	TagId uint64 `json:"tagId,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PostTagQuery when eager-loading is set.
	Edges        PostTagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PostTagEdges holds the relations/edges for other nodes in the graph.
type PostTagEdges struct {
	// Post holds the value of the post edge.
	Post *Post `json:"post,omitempty"`
	// Tag holds the value of the tag edge.
	Tag *Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PostOrErr returns the Post value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostTagEdges) PostOrErr() (*Post, error) {
	if e.Post != nil {
		return e.Post, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: post.Label}
	}
	return nil, &NotLoadedError{edge: "post"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PostTagEdges) TagOrErr() (*Tag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PostTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case posttag.FieldID, posttag.FieldPostId, posttag.FieldTagId:
			values[i] = new(sql.NullInt64)
		case posttag.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PostTag fields.
func (_m *PostTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case posttag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case posttag.FieldPostId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field postId", values[i])
			} else if value.Valid {
				_m.PostId = uint64(value.Int64)
			}
		case posttag.FieldTagId:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tagId", values[i])
			} else if value.Valid {
				_m.TagId = uint64(value.Int64)
			}
		case posttag.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PostTag.
// This includes values selected through modifiers, order, etc.
func (_m *PostTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPost queries the "post" edge of the PostTag entity.
func (_m *PostTag) QueryPost() *PostQuery {
	return NewPostTagClient(_m.config).QueryPost(_m)
}

// QueryTag queries the "tag" edge of the PostTag entity.
func (_m *PostTag) QueryTag() *TagQuery {
	return NewPostTagClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this PostTag.
// Note that you need to call PostTag.Unwrap() before calling this method if this PostTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PostTag) Update() *PostTagUpdateOne {
	return NewPostTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PostTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PostTag) Unwrap() *PostTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PostTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PostTag) String() string {
	var builder strings.Builder
	builder.WriteString("PostTag(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("postId=")
	builder.WriteString(fmt.Sprintf("%v", _m.PostId))
	builder.WriteString(", ")
	builder.WriteString("tagId=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagId))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PostTags is a parsable slice of PostTag.
type PostTags []*PostTag
