// Code generated by ent, DO NOT EDIT.

package ent

import (
	"blog-server/internal/ent/dictitem"
	"blog-server/internal/ent/operationlog"
	"blog-server/internal/ent/schema"
	"blog-server/internal/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	dictitemFields := schema.DictItem{}.Fields()
	_ = dictitemFields
	// dictitemDescDictType is the schema descriptor for dictType field.
	dictitemDescDictType := dictitemFields[1].Descriptor()
	// dictitem.DictTypeValidator is a validator for the "dictType" field. It is called by the builders before save.
	dictitem.DictTypeValidator = func() func(string) error {
		validators := dictitemDescDictType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(dictType string) error {
			for _, fn := range fns {
				if err := fn(dictType); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictitemDescValue is the schema descriptor for value field.
	dictitemDescValue := dictitemFields[2].Descriptor()
	// dictitem.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	dictitem.ValueValidator = dictitemDescValue.Validators[0].(func(int) error)
	// dictitemDescLabel is the schema descriptor for label field.
	dictitemDescLabel := dictitemFields[3].Descriptor()
	// dictitem.LabelValidator is a validator for the "label" field. It is called by the builders before save.
	dictitem.LabelValidator = func() func(string) error {
		validators := dictitemDescLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(label string) error {
			for _, fn := range fns {
				if err := fn(label); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// dictitemDescEnabled is the schema descriptor for enabled field.
	dictitemDescEnabled := dictitemFields[4].Descriptor()
	// dictitem.DefaultEnabled holds the default value on creation for the enabled field.
	dictitem.DefaultEnabled = dictitemDescEnabled.Default.(bool)
	// dictitemDescSort is the schema descriptor for sort field.
	dictitemDescSort := dictitemFields[5].Descriptor()
	// dictitem.DefaultSort holds the default value on creation for the sort field.
	dictitem.DefaultSort = dictitemDescSort.Default.(int)
	// dictitemDescCreatedAt is the schema descriptor for createdAt field.
	dictitemDescCreatedAt := dictitemFields[6].Descriptor()
	// dictitem.DefaultCreatedAt holds the default value on creation for the createdAt field.
	dictitem.DefaultCreatedAt = dictitemDescCreatedAt.Default.(func() time.Time)
	// dictitemDescUpdatedAt is the schema descriptor for updatedAt field.
	dictitemDescUpdatedAt := dictitemFields[7].Descriptor()
	// dictitem.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	dictitem.DefaultUpdatedAt = dictitemDescUpdatedAt.Default.(func() time.Time)
	// dictitem.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	dictitem.UpdateDefaultUpdatedAt = dictitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	operationlogFields := schema.OperationLog{}.Fields()
	_ = operationlogFields
	// operationlogDescUsername is the schema descriptor for username field.
	operationlogDescUsername := operationlogFields[2].Descriptor()
	// operationlog.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	operationlog.UsernameValidator = func() func(string) error {
		validators := operationlogDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescActionValue is the schema descriptor for actionValue field.
	operationlogDescActionValue := operationlogFields[3].Descriptor()
	// operationlog.ActionValueValidator is a validator for the "actionValue" field. It is called by the builders before save.
	operationlog.ActionValueValidator = operationlogDescActionValue.Validators[0].(func(int) error)
	// operationlogDescActionLabel is the schema descriptor for actionLabel field.
	operationlogDescActionLabel := operationlogFields[4].Descriptor()
	// operationlog.ActionLabelValidator is a validator for the "actionLabel" field. It is called by the builders before save.
	operationlog.ActionLabelValidator = func() func(string) error {
		validators := operationlogDescActionLabel.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(actionLabel string) error {
			for _, fn := range fns {
				if err := fn(actionLabel); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescIP is the schema descriptor for ip field.
	operationlogDescIP := operationlogFields[5].Descriptor()
	// operationlog.IPValidator is a validator for the "ip" field. It is called by the builders before save.
	operationlog.IPValidator = func() func(string) error {
		validators := operationlogDescIP.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(ip string) error {
			for _, fn := range fns {
				if err := fn(ip); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// operationlogDescRegion is the schema descriptor for region field.
	operationlogDescRegion := operationlogFields[6].Descriptor()
	// operationlog.DefaultRegion holds the default value on creation for the region field.
	operationlog.DefaultRegion = operationlogDescRegion.Default.(string)
	// operationlog.RegionValidator is a validator for the "region" field. It is called by the builders before save.
	operationlog.RegionValidator = operationlogDescRegion.Validators[0].(func(string) error)
	// operationlogDescUserAgent is the schema descriptor for userAgent field.
	operationlogDescUserAgent := operationlogFields[7].Descriptor()
	// operationlog.DefaultUserAgent holds the default value on creation for the userAgent field.
	operationlog.DefaultUserAgent = operationlogDescUserAgent.Default.(string)
	// operationlog.UserAgentValidator is a validator for the "userAgent" field. It is called by the builders before save.
	operationlog.UserAgentValidator = operationlogDescUserAgent.Validators[0].(func(string) error)
	// operationlogDescCreatedAt is the schema descriptor for createdAt field.
	operationlogDescCreatedAt := operationlogFields[8].Descriptor()
	// operationlog.DefaultCreatedAt holds the default value on creation for the createdAt field.
	operationlog.DefaultCreatedAt = operationlogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for passwordHash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "passwordHash" field. It is called by the builders before save.
	user.PasswordHashValidator = func() func(string) error {
		validators := userDescPasswordHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(passwordHash string) error {
			for _, fn := range fns {
				if err := fn(passwordHash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[3].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = func() func(string) error {
		validators := userDescNickname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nickname string) error {
			for _, fn := range fns {
				if err := fn(nickname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[4].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// user.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	user.AvatarValidator = userDescAvatar.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[5].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[6].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(string)
	// user.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user.StatusValidator = userDescStatus.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updatedAt field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
