// Code generated by ent, DO NOT EDIT.

package musictrack

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the musictrack type in the database.
	Label = "music_track"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldArtist holds the string denoting the artist field in the database.
	FieldArtist = "artist"
	// FieldAudioUrl holds the string denoting the audiourl field in the database.
	FieldAudioUrl = "audioUrl"
	// FieldCoverUrl holds the string denoting the coverurl field in the database.
	FieldCoverUrl = "coverUrl"
	// FieldLrc holds the string denoting the lrc field in the database.
	FieldLrc = "lrc"
	// FieldDurationSeconds holds the string denoting the durationseconds field in the database.
	FieldDurationSeconds = "durationSeconds"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldVisible holds the string denoting the visible field in the database.
	FieldVisible = "visible"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updatedAt"
	// FieldDeletedAt holds the string denoting the deletedat field in the database.
	FieldDeletedAt = "deletedAt"
	// Table holds the table name of the musictrack in the database.
	Table = "musicTracks"
)

// Columns holds all SQL columns for musictrack fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldArtist,
	FieldAudioUrl,
	FieldCoverUrl,
	FieldLrc,
	FieldDurationSeconds,
	FieldSort,
	FieldVisible,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultArtist holds the default value on creation for the "artist" field.
	DefaultArtist string
	// ArtistValidator is a validator for the "artist" field. It is called by the builders before save.
	ArtistValidator func(string) error
	// AudioUrlValidator is a validator for the "audioUrl" field. It is called by the builders before save.
	AudioUrlValidator func(string) error
	// DefaultCoverUrl holds the default value on creation for the "coverUrl" field.
	DefaultCoverUrl string
	// CoverUrlValidator is a validator for the "coverUrl" field. It is called by the builders before save.
	CoverUrlValidator func(string) error
	// DefaultDurationSeconds holds the default value on creation for the "durationSeconds" field.
	DefaultDurationSeconds int
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int
	// DefaultVisible holds the default value on creation for the "visible" field.
	DefaultVisible bool
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the MusicTrack queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByArtist orders the results by the artist field.
func ByArtist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtist, opts...).ToFunc()
}

// ByAudioUrl orders the results by the audioUrl field.
func ByAudioUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudioUrl, opts...).ToFunc()
}

// ByCoverUrl orders the results by the coverUrl field.
func ByCoverUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverUrl, opts...).ToFunc()
}

// ByLrc orders the results by the lrc field.
func ByLrc(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLrc, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the durationSeconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByVisible orders the results by the visible field.
func ByVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVisible, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deletedAt field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}
