// Code generated by ent, DO NOT EDIT.

package musictrack

import (
	"blog-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldName, v))
}

// Artist applies equality check predicate on the "artist" field. It's identical to ArtistEQ.
func Artist(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldArtist, v))
}

// AudioUrl applies equality check predicate on the "audioUrl" field. It's identical to AudioUrlEQ.
func AudioUrl(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldAudioUrl, v))
}

// CoverUrl applies equality check predicate on the "coverUrl" field. It's identical to CoverUrlEQ.
func CoverUrl(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldCoverUrl, v))
}

// Lrc applies equality check predicate on the "lrc" field. It's identical to LrcEQ.
func Lrc(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldLrc, v))
}

// DurationSeconds applies equality check predicate on the "durationSeconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldDurationSeconds, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldSort, v))
}

// Visible applies equality check predicate on the "visible" field. It's identical to VisibleEQ.
func Visible(v bool) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldVisible, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deletedAt" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldDeletedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContainsFold(FieldName, v))
}

// ArtistEQ applies the EQ predicate on the "artist" field.
func ArtistEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldArtist, v))
}

// ArtistNEQ applies the NEQ predicate on the "artist" field.
func ArtistNEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldArtist, v))
}

// ArtistIn applies the In predicate on the "artist" field.
func ArtistIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldArtist, vs...))
}

// ArtistNotIn applies the NotIn predicate on the "artist" field.
func ArtistNotIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldArtist, vs...))
}

// ArtistGT applies the GT predicate on the "artist" field.
func ArtistGT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldArtist, v))
}

// ArtistGTE applies the GTE predicate on the "artist" field.
func ArtistGTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldArtist, v))
}

// ArtistLT applies the LT predicate on the "artist" field.
func ArtistLT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldArtist, v))
}

// ArtistLTE applies the LTE predicate on the "artist" field.
func ArtistLTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldArtist, v))
}

// ArtistContains applies the Contains predicate on the "artist" field.
func ArtistContains(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContains(FieldArtist, v))
}

// ArtistHasPrefix applies the HasPrefix predicate on the "artist" field.
func ArtistHasPrefix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasPrefix(FieldArtist, v))
}

// ArtistHasSuffix applies the HasSuffix predicate on the "artist" field.
func ArtistHasSuffix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasSuffix(FieldArtist, v))
}

// ArtistEqualFold applies the EqualFold predicate on the "artist" field.
func ArtistEqualFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEqualFold(FieldArtist, v))
}

// ArtistContainsFold applies the ContainsFold predicate on the "artist" field.
func ArtistContainsFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContainsFold(FieldArtist, v))
}

// AudioUrlEQ applies the EQ predicate on the "audioUrl" field.
func AudioUrlEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldAudioUrl, v))
}

// AudioUrlNEQ applies the NEQ predicate on the "audioUrl" field.
func AudioUrlNEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldAudioUrl, v))
}

// AudioUrlIn applies the In predicate on the "audioUrl" field.
func AudioUrlIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldAudioUrl, vs...))
}

// AudioUrlNotIn applies the NotIn predicate on the "audioUrl" field.
func AudioUrlNotIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldAudioUrl, vs...))
}

// AudioUrlGT applies the GT predicate on the "audioUrl" field.
func AudioUrlGT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldAudioUrl, v))
}

// AudioUrlGTE applies the GTE predicate on the "audioUrl" field.
func AudioUrlGTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldAudioUrl, v))
}

// AudioUrlLT applies the LT predicate on the "audioUrl" field.
func AudioUrlLT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldAudioUrl, v))
}

// AudioUrlLTE applies the LTE predicate on the "audioUrl" field.
func AudioUrlLTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldAudioUrl, v))
}

// AudioUrlContains applies the Contains predicate on the "audioUrl" field.
func AudioUrlContains(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContains(FieldAudioUrl, v))
}

// AudioUrlHasPrefix applies the HasPrefix predicate on the "audioUrl" field.
func AudioUrlHasPrefix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasPrefix(FieldAudioUrl, v))
}

// AudioUrlHasSuffix applies the HasSuffix predicate on the "audioUrl" field.
func AudioUrlHasSuffix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasSuffix(FieldAudioUrl, v))
}

// AudioUrlEqualFold applies the EqualFold predicate on the "audioUrl" field.
func AudioUrlEqualFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEqualFold(FieldAudioUrl, v))
}

// AudioUrlContainsFold applies the ContainsFold predicate on the "audioUrl" field.
func AudioUrlContainsFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContainsFold(FieldAudioUrl, v))
}

// CoverUrlEQ applies the EQ predicate on the "coverUrl" field.
func CoverUrlEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldCoverUrl, v))
}

// CoverUrlNEQ applies the NEQ predicate on the "coverUrl" field.
func CoverUrlNEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldCoverUrl, v))
}

// CoverUrlIn applies the In predicate on the "coverUrl" field.
func CoverUrlIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldCoverUrl, vs...))
}

// CoverUrlNotIn applies the NotIn predicate on the "coverUrl" field.
func CoverUrlNotIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldCoverUrl, vs...))
}

// CoverUrlGT applies the GT predicate on the "coverUrl" field.
func CoverUrlGT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldCoverUrl, v))
}

// CoverUrlGTE applies the GTE predicate on the "coverUrl" field.
func CoverUrlGTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldCoverUrl, v))
}

// CoverUrlLT applies the LT predicate on the "coverUrl" field.
func CoverUrlLT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldCoverUrl, v))
}

// CoverUrlLTE applies the LTE predicate on the "coverUrl" field.
func CoverUrlLTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldCoverUrl, v))
}

// CoverUrlContains applies the Contains predicate on the "coverUrl" field.
func CoverUrlContains(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContains(FieldCoverUrl, v))
}

// CoverUrlHasPrefix applies the HasPrefix predicate on the "coverUrl" field.
func CoverUrlHasPrefix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasPrefix(FieldCoverUrl, v))
}

// CoverUrlHasSuffix applies the HasSuffix predicate on the "coverUrl" field.
func CoverUrlHasSuffix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasSuffix(FieldCoverUrl, v))
}

// CoverUrlIsNil applies the IsNil predicate on the "coverUrl" field.
func CoverUrlIsNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIsNull(FieldCoverUrl))
}

// CoverUrlNotNil applies the NotNil predicate on the "coverUrl" field.
func CoverUrlNotNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotNull(FieldCoverUrl))
}

// CoverUrlEqualFold applies the EqualFold predicate on the "coverUrl" field.
func CoverUrlEqualFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEqualFold(FieldCoverUrl, v))
}

// CoverUrlContainsFold applies the ContainsFold predicate on the "coverUrl" field.
func CoverUrlContainsFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContainsFold(FieldCoverUrl, v))
}

// LrcEQ applies the EQ predicate on the "lrc" field.
func LrcEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldLrc, v))
}

// LrcNEQ applies the NEQ predicate on the "lrc" field.
func LrcNEQ(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldLrc, v))
}

// LrcIn applies the In predicate on the "lrc" field.
func LrcIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldLrc, vs...))
}

// LrcNotIn applies the NotIn predicate on the "lrc" field.
func LrcNotIn(vs ...string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldLrc, vs...))
}

// LrcGT applies the GT predicate on the "lrc" field.
func LrcGT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldLrc, v))
}

// LrcGTE applies the GTE predicate on the "lrc" field.
func LrcGTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldLrc, v))
}

// LrcLT applies the LT predicate on the "lrc" field.
func LrcLT(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldLrc, v))
}

// LrcLTE applies the LTE predicate on the "lrc" field.
func LrcLTE(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldLrc, v))
}

// LrcContains applies the Contains predicate on the "lrc" field.
func LrcContains(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContains(FieldLrc, v))
}

// LrcHasPrefix applies the HasPrefix predicate on the "lrc" field.
func LrcHasPrefix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasPrefix(FieldLrc, v))
}

// LrcHasSuffix applies the HasSuffix predicate on the "lrc" field.
func LrcHasSuffix(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldHasSuffix(FieldLrc, v))
}

// LrcIsNil applies the IsNil predicate on the "lrc" field.
func LrcIsNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIsNull(FieldLrc))
}

// LrcNotNil applies the NotNil predicate on the "lrc" field.
func LrcNotNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotNull(FieldLrc))
}

// LrcEqualFold applies the EqualFold predicate on the "lrc" field.
func LrcEqualFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEqualFold(FieldLrc, v))
}

// LrcContainsFold applies the ContainsFold predicate on the "lrc" field.
func LrcContainsFold(v string) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldContainsFold(FieldLrc, v))
}

// DurationSecondsEQ applies the EQ predicate on the "durationSeconds" field.
func DurationSecondsEQ(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "durationSeconds" field.
func DurationSecondsNEQ(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "durationSeconds" field.
func DurationSecondsIn(vs ...int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "durationSeconds" field.
func DurationSecondsNotIn(vs ...int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "durationSeconds" field.
func DurationSecondsGT(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "durationSeconds" field.
func DurationSecondsGTE(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "durationSeconds" field.
func DurationSecondsLT(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "durationSeconds" field.
func DurationSecondsLTE(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldDurationSeconds, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldSort, v))
}

// VisibleEQ applies the EQ predicate on the "visible" field.
func VisibleEQ(v bool) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldVisible, v))
}

// VisibleNEQ applies the NEQ predicate on the "visible" field.
func VisibleNEQ(v bool) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldVisible, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deletedAt" field.
func DeletedAtEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deletedAt" field.
func DeletedAtNEQ(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deletedAt" field.
func DeletedAtIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deletedAt" field.
func DeletedAtNotIn(vs ...time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deletedAt" field.
func DeletedAtGT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deletedAt" field.
func DeletedAtGTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deletedAt" field.
func DeletedAtLT(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deletedAt" field.
func DeletedAtLTE(v time.Time) predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deletedAt" field.
func DeletedAtIsNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deletedAt" field.
func DeletedAtNotNil() predicate.MusicTrack {
	return predicate.MusicTrack(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MusicTrack) predicate.MusicTrack {
	return predicate.MusicTrack(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MusicTrack) predicate.MusicTrack {
	return predicate.MusicTrack(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MusicTrack) predicate.MusicTrack {
	return predicate.MusicTrack(sql.NotPredicates(p))
}
