// Code generated by ent, DO NOT EDIT.

package sitesetting

import (
	"blog-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLTE(FieldID, id))
}

// SettingKey applies equality check predicate on the "settingKey" field. It's identical to SettingKeyEQ.
func SettingKey(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldSettingKey, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// SettingKeyEQ applies the EQ predicate on the "settingKey" field.
func SettingKeyEQ(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldSettingKey, v))
}

// SettingKeyNEQ applies the NEQ predicate on the "settingKey" field.
func SettingKeyNEQ(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNEQ(FieldSettingKey, v))
}

// SettingKeyIn applies the In predicate on the "settingKey" field.
func SettingKeyIn(vs ...string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIn(FieldSettingKey, vs...))
}

// SettingKeyNotIn applies the NotIn predicate on the "settingKey" field.
func SettingKeyNotIn(vs ...string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotIn(FieldSettingKey, vs...))
}

// SettingKeyGT applies the GT predicate on the "settingKey" field.
func SettingKeyGT(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGT(FieldSettingKey, v))
}

// SettingKeyGTE applies the GTE predicate on the "settingKey" field.
func SettingKeyGTE(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGTE(FieldSettingKey, v))
}

// SettingKeyLT applies the LT predicate on the "settingKey" field.
func SettingKeyLT(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLT(FieldSettingKey, v))
}

// SettingKeyLTE applies the LTE predicate on the "settingKey" field.
func SettingKeyLTE(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLTE(FieldSettingKey, v))
}

// SettingKeyContains applies the Contains predicate on the "settingKey" field.
func SettingKeyContains(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldContains(FieldSettingKey, v))
}

// SettingKeyHasPrefix applies the HasPrefix predicate on the "settingKey" field.
func SettingKeyHasPrefix(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldHasPrefix(FieldSettingKey, v))
}

// SettingKeyHasSuffix applies the HasSuffix predicate on the "settingKey" field.
func SettingKeyHasSuffix(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldHasSuffix(FieldSettingKey, v))
}

// SettingKeyEqualFold applies the EqualFold predicate on the "settingKey" field.
func SettingKeyEqualFold(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEqualFold(FieldSettingKey, v))
}

// SettingKeyContainsFold applies the ContainsFold predicate on the "settingKey" field.
func SettingKeyContainsFold(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldContainsFold(FieldSettingKey, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.SiteSetting {
	return predicate.SiteSetting(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SiteSetting) predicate.SiteSetting {
	return predicate.SiteSetting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SiteSetting) predicate.SiteSetting {
	return predicate.SiteSetting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SiteSetting) predicate.SiteSetting {
	return predicate.SiteSetting(sql.NotPredicates(p))
}
