// Code generated by ent, DO NOT EDIT.

package game

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the game type in the database.
	Label = "game"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSteamAppId holds the string denoting the steamappid field in the database.
	FieldSteamAppId = "steamAppId"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameZh holds the string denoting the namezh field in the database.
	FieldNameZh = "nameZh"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldGenres holds the string denoting the genres field in the database.
	FieldGenres = "genres"
	// FieldPlaytimeMinutes holds the string denoting the playtimeminutes field in the database.
	FieldPlaytimeMinutes = "playtimeMinutes"
	// FieldPlaytime2WeeksMinutes holds the string denoting the playtime2weeksminutes field in the database.
	FieldPlaytime2WeeksMinutes = "playtime2WeeksMinutes"
	// FieldLastPlayedAt holds the string denoting the lastplayedat field in the database.
	FieldLastPlayedAt = "lastPlayedAt"
	// FieldAchievementUnlocked holds the string denoting the achievementunlocked field in the database.
	FieldAchievementUnlocked = "achievementUnlocked"
	// FieldAchievementTotal holds the string denoting the achievementtotal field in the database.
	FieldAchievementTotal = "achievementTotal"
	// FieldProgressPercent holds the string denoting the progresspercent field in the database.
	FieldProgressPercent = "progressPercent"
	// FieldProgressSource holds the string denoting the progresssource field in the database.
	FieldProgressSource = "progressSource"
	// FieldPlayStatus holds the string denoting the playstatus field in the database.
	FieldPlayStatus = "playStatus"
	// FieldIsVisible holds the string denoting the isvisible field in the database.
	FieldIsVisible = "isVisible"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldSyncedAt holds the string denoting the syncedat field in the database.
	FieldSyncedAt = "syncedAt"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "createdAt"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updatedAt"
	// Table holds the table name of the game in the database.
	Table = "games"
)

// Columns holds all SQL columns for game fields.
var Columns = []string{
	FieldID,
	FieldSteamAppId,
	FieldName,
	FieldNameZh,
	FieldCover,
	FieldGenres,
	FieldPlaytimeMinutes,
	FieldPlaytime2WeeksMinutes,
	FieldLastPlayedAt,
	FieldAchievementUnlocked,
	FieldAchievementTotal,
	FieldProgressPercent,
	FieldProgressSource,
	FieldPlayStatus,
	FieldIsVisible,
	FieldSort,
	FieldSyncedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// NameZhValidator is a validator for the "nameZh" field. It is called by the builders before save.
	NameZhValidator func(string) error
	// DefaultCover holds the default value on creation for the "cover" field.
	DefaultCover string
	// CoverValidator is a validator for the "cover" field. It is called by the builders before save.
	CoverValidator func(string) error
	// DefaultGenres holds the default value on creation for the "genres" field.
	DefaultGenres []string
	// DefaultPlaytimeMinutes holds the default value on creation for the "playtimeMinutes" field.
	DefaultPlaytimeMinutes uint32
	// DefaultPlaytime2WeeksMinutes holds the default value on creation for the "playtime2WeeksMinutes" field.
	DefaultPlaytime2WeeksMinutes uint32
	// DefaultProgressSource holds the default value on creation for the "progressSource" field.
	DefaultProgressSource string
	// ProgressSourceValidator is a validator for the "progressSource" field. It is called by the builders before save.
	ProgressSourceValidator func(string) error
	// DefaultPlayStatus holds the default value on creation for the "playStatus" field.
	DefaultPlayStatus string
	// PlayStatusValidator is a validator for the "playStatus" field. It is called by the builders before save.
	PlayStatusValidator func(string) error
	// DefaultIsVisible holds the default value on creation for the "isVisible" field.
	DefaultIsVisible bool
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Game queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySteamAppId orders the results by the steamAppId field.
func BySteamAppId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSteamAppId, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameZh orders the results by the nameZh field.
func ByNameZh(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameZh, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByPlaytimeMinutes orders the results by the playtimeMinutes field.
func ByPlaytimeMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaytimeMinutes, opts...).ToFunc()
}

// ByPlaytime2WeeksMinutes orders the results by the playtime2WeeksMinutes field.
func ByPlaytime2WeeksMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlaytime2WeeksMinutes, opts...).ToFunc()
}

// ByLastPlayedAt orders the results by the lastPlayedAt field.
func ByLastPlayedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPlayedAt, opts...).ToFunc()
}

// ByAchievementUnlocked orders the results by the achievementUnlocked field.
func ByAchievementUnlocked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAchievementUnlocked, opts...).ToFunc()
}

// ByAchievementTotal orders the results by the achievementTotal field.
func ByAchievementTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAchievementTotal, opts...).ToFunc()
}

// ByProgressPercent orders the results by the progressPercent field.
func ByProgressPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgressPercent, opts...).ToFunc()
}

// ByProgressSource orders the results by the progressSource field.
func ByProgressSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgressSource, opts...).ToFunc()
}

// ByPlayStatus orders the results by the playStatus field.
func ByPlayStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayStatus, opts...).ToFunc()
}

// ByIsVisible orders the results by the isVisible field.
func ByIsVisible(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVisible, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// BySyncedAt orders the results by the syncedAt field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
