// Code generated by ent, DO NOT EDIT.

package game

import (
	"blog-server/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldID, id))
}

// SteamAppId applies equality check predicate on the "steamAppId" field. It's identical to SteamAppIdEQ.
func SteamAppId(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSteamAppId, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// NameZh applies equality check predicate on the "nameZh" field. It's identical to NameZhEQ.
func NameZh(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNameZh, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCover, v))
}

// PlaytimeMinutes applies equality check predicate on the "playtimeMinutes" field. It's identical to PlaytimeMinutesEQ.
func PlaytimeMinutes(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlaytimeMinutes, v))
}

// Playtime2WeeksMinutes applies equality check predicate on the "playtime2WeeksMinutes" field. It's identical to Playtime2WeeksMinutesEQ.
func Playtime2WeeksMinutes(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlaytime2WeeksMinutes, v))
}

// LastPlayedAt applies equality check predicate on the "lastPlayedAt" field. It's identical to LastPlayedAtEQ.
func LastPlayedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldLastPlayedAt, v))
}

// AchievementUnlocked applies equality check predicate on the "achievementUnlocked" field. It's identical to AchievementUnlockedEQ.
func AchievementUnlocked(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldAchievementUnlocked, v))
}

// AchievementTotal applies equality check predicate on the "achievementTotal" field. It's identical to AchievementTotalEQ.
func AchievementTotal(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldAchievementTotal, v))
}

// ProgressPercent applies equality check predicate on the "progressPercent" field. It's identical to ProgressPercentEQ.
func ProgressPercent(v uint8) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressSource applies equality check predicate on the "progressSource" field. It's identical to ProgressSourceEQ.
func ProgressSource(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProgressSource, v))
}

// PlayStatus applies equality check predicate on the "playStatus" field. It's identical to PlayStatusEQ.
func PlayStatus(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayStatus, v))
}

// IsVisible applies equality check predicate on the "isVisible" field. It's identical to IsVisibleEQ.
func IsVisible(v bool) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldIsVisible, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSort, v))
}

// SyncedAt applies equality check predicate on the "syncedAt" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// SteamAppIdEQ applies the EQ predicate on the "steamAppId" field.
func SteamAppIdEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSteamAppId, v))
}

// SteamAppIdNEQ applies the NEQ predicate on the "steamAppId" field.
func SteamAppIdNEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldSteamAppId, v))
}

// SteamAppIdIn applies the In predicate on the "steamAppId" field.
func SteamAppIdIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldSteamAppId, vs...))
}

// SteamAppIdNotIn applies the NotIn predicate on the "steamAppId" field.
func SteamAppIdNotIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldSteamAppId, vs...))
}

// SteamAppIdGT applies the GT predicate on the "steamAppId" field.
func SteamAppIdGT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldSteamAppId, v))
}

// SteamAppIdGTE applies the GTE predicate on the "steamAppId" field.
func SteamAppIdGTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldSteamAppId, v))
}

// SteamAppIdLT applies the LT predicate on the "steamAppId" field.
func SteamAppIdLT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldSteamAppId, v))
}

// SteamAppIdLTE applies the LTE predicate on the "steamAppId" field.
func SteamAppIdLTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldSteamAppId, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldName, v))
}

// NameZhEQ applies the EQ predicate on the "nameZh" field.
func NameZhEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldNameZh, v))
}

// NameZhNEQ applies the NEQ predicate on the "nameZh" field.
func NameZhNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldNameZh, v))
}

// NameZhIn applies the In predicate on the "nameZh" field.
func NameZhIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldNameZh, vs...))
}

// NameZhNotIn applies the NotIn predicate on the "nameZh" field.
func NameZhNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldNameZh, vs...))
}

// NameZhGT applies the GT predicate on the "nameZh" field.
func NameZhGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldNameZh, v))
}

// NameZhGTE applies the GTE predicate on the "nameZh" field.
func NameZhGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldNameZh, v))
}

// NameZhLT applies the LT predicate on the "nameZh" field.
func NameZhLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldNameZh, v))
}

// NameZhLTE applies the LTE predicate on the "nameZh" field.
func NameZhLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldNameZh, v))
}

// NameZhContains applies the Contains predicate on the "nameZh" field.
func NameZhContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldNameZh, v))
}

// NameZhHasPrefix applies the HasPrefix predicate on the "nameZh" field.
func NameZhHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldNameZh, v))
}

// NameZhHasSuffix applies the HasSuffix predicate on the "nameZh" field.
func NameZhHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldNameZh, v))
}

// NameZhIsNil applies the IsNil predicate on the "nameZh" field.
func NameZhIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldNameZh))
}

// NameZhNotNil applies the NotNil predicate on the "nameZh" field.
func NameZhNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldNameZh))
}

// NameZhEqualFold applies the EqualFold predicate on the "nameZh" field.
func NameZhEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldNameZh, v))
}

// NameZhContainsFold applies the ContainsFold predicate on the "nameZh" field.
func NameZhContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldNameZh, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldCover, v))
}

// CoverIsNil applies the IsNil predicate on the "cover" field.
func CoverIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldCover))
}

// CoverNotNil applies the NotNil predicate on the "cover" field.
func CoverNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldCover))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldCover, v))
}

// PlaytimeMinutesEQ applies the EQ predicate on the "playtimeMinutes" field.
func PlaytimeMinutesEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlaytimeMinutes, v))
}

// PlaytimeMinutesNEQ applies the NEQ predicate on the "playtimeMinutes" field.
func PlaytimeMinutesNEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldPlaytimeMinutes, v))
}

// PlaytimeMinutesIn applies the In predicate on the "playtimeMinutes" field.
func PlaytimeMinutesIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldPlaytimeMinutes, vs...))
}

// PlaytimeMinutesNotIn applies the NotIn predicate on the "playtimeMinutes" field.
func PlaytimeMinutesNotIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldPlaytimeMinutes, vs...))
}

// PlaytimeMinutesGT applies the GT predicate on the "playtimeMinutes" field.
func PlaytimeMinutesGT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldPlaytimeMinutes, v))
}

// PlaytimeMinutesGTE applies the GTE predicate on the "playtimeMinutes" field.
func PlaytimeMinutesGTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldPlaytimeMinutes, v))
}

// PlaytimeMinutesLT applies the LT predicate on the "playtimeMinutes" field.
func PlaytimeMinutesLT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldPlaytimeMinutes, v))
}

// PlaytimeMinutesLTE applies the LTE predicate on the "playtimeMinutes" field.
func PlaytimeMinutesLTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldPlaytimeMinutes, v))
}

// Playtime2WeeksMinutesEQ applies the EQ predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlaytime2WeeksMinutes, v))
}

// Playtime2WeeksMinutesNEQ applies the NEQ predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesNEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldPlaytime2WeeksMinutes, v))
}

// Playtime2WeeksMinutesIn applies the In predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldPlaytime2WeeksMinutes, vs...))
}

// Playtime2WeeksMinutesNotIn applies the NotIn predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesNotIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldPlaytime2WeeksMinutes, vs...))
}

// Playtime2WeeksMinutesGT applies the GT predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesGT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldPlaytime2WeeksMinutes, v))
}

// Playtime2WeeksMinutesGTE applies the GTE predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesGTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldPlaytime2WeeksMinutes, v))
}

// Playtime2WeeksMinutesLT applies the LT predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesLT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldPlaytime2WeeksMinutes, v))
}

// Playtime2WeeksMinutesLTE applies the LTE predicate on the "playtime2WeeksMinutes" field.
func Playtime2WeeksMinutesLTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldPlaytime2WeeksMinutes, v))
}

// LastPlayedAtEQ applies the EQ predicate on the "lastPlayedAt" field.
func LastPlayedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldLastPlayedAt, v))
}

// LastPlayedAtNEQ applies the NEQ predicate on the "lastPlayedAt" field.
func LastPlayedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldLastPlayedAt, v))
}

// LastPlayedAtIn applies the In predicate on the "lastPlayedAt" field.
func LastPlayedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldLastPlayedAt, vs...))
}

// LastPlayedAtNotIn applies the NotIn predicate on the "lastPlayedAt" field.
func LastPlayedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldLastPlayedAt, vs...))
}

// LastPlayedAtGT applies the GT predicate on the "lastPlayedAt" field.
func LastPlayedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldLastPlayedAt, v))
}

// LastPlayedAtGTE applies the GTE predicate on the "lastPlayedAt" field.
func LastPlayedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldLastPlayedAt, v))
}

// LastPlayedAtLT applies the LT predicate on the "lastPlayedAt" field.
func LastPlayedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldLastPlayedAt, v))
}

// LastPlayedAtLTE applies the LTE predicate on the "lastPlayedAt" field.
func LastPlayedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldLastPlayedAt, v))
}

// LastPlayedAtIsNil applies the IsNil predicate on the "lastPlayedAt" field.
func LastPlayedAtIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldLastPlayedAt))
}

// LastPlayedAtNotNil applies the NotNil predicate on the "lastPlayedAt" field.
func LastPlayedAtNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldLastPlayedAt))
}

// AchievementUnlockedEQ applies the EQ predicate on the "achievementUnlocked" field.
func AchievementUnlockedEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldAchievementUnlocked, v))
}

// AchievementUnlockedNEQ applies the NEQ predicate on the "achievementUnlocked" field.
func AchievementUnlockedNEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldAchievementUnlocked, v))
}

// AchievementUnlockedIn applies the In predicate on the "achievementUnlocked" field.
func AchievementUnlockedIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldAchievementUnlocked, vs...))
}

// AchievementUnlockedNotIn applies the NotIn predicate on the "achievementUnlocked" field.
func AchievementUnlockedNotIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldAchievementUnlocked, vs...))
}

// AchievementUnlockedGT applies the GT predicate on the "achievementUnlocked" field.
func AchievementUnlockedGT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldAchievementUnlocked, v))
}

// AchievementUnlockedGTE applies the GTE predicate on the "achievementUnlocked" field.
func AchievementUnlockedGTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldAchievementUnlocked, v))
}

// AchievementUnlockedLT applies the LT predicate on the "achievementUnlocked" field.
func AchievementUnlockedLT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldAchievementUnlocked, v))
}

// AchievementUnlockedLTE applies the LTE predicate on the "achievementUnlocked" field.
func AchievementUnlockedLTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldAchievementUnlocked, v))
}

// AchievementUnlockedIsNil applies the IsNil predicate on the "achievementUnlocked" field.
func AchievementUnlockedIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldAchievementUnlocked))
}

// AchievementUnlockedNotNil applies the NotNil predicate on the "achievementUnlocked" field.
func AchievementUnlockedNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldAchievementUnlocked))
}

// AchievementTotalEQ applies the EQ predicate on the "achievementTotal" field.
func AchievementTotalEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldAchievementTotal, v))
}

// AchievementTotalNEQ applies the NEQ predicate on the "achievementTotal" field.
func AchievementTotalNEQ(v uint32) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldAchievementTotal, v))
}

// AchievementTotalIn applies the In predicate on the "achievementTotal" field.
func AchievementTotalIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldAchievementTotal, vs...))
}

// AchievementTotalNotIn applies the NotIn predicate on the "achievementTotal" field.
func AchievementTotalNotIn(vs ...uint32) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldAchievementTotal, vs...))
}

// AchievementTotalGT applies the GT predicate on the "achievementTotal" field.
func AchievementTotalGT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldAchievementTotal, v))
}

// AchievementTotalGTE applies the GTE predicate on the "achievementTotal" field.
func AchievementTotalGTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldAchievementTotal, v))
}

// AchievementTotalLT applies the LT predicate on the "achievementTotal" field.
func AchievementTotalLT(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldAchievementTotal, v))
}

// AchievementTotalLTE applies the LTE predicate on the "achievementTotal" field.
func AchievementTotalLTE(v uint32) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldAchievementTotal, v))
}

// AchievementTotalIsNil applies the IsNil predicate on the "achievementTotal" field.
func AchievementTotalIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldAchievementTotal))
}

// AchievementTotalNotNil applies the NotNil predicate on the "achievementTotal" field.
func AchievementTotalNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldAchievementTotal))
}

// ProgressPercentEQ applies the EQ predicate on the "progressPercent" field.
func ProgressPercentEQ(v uint8) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProgressPercent, v))
}

// ProgressPercentNEQ applies the NEQ predicate on the "progressPercent" field.
func ProgressPercentNEQ(v uint8) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldProgressPercent, v))
}

// ProgressPercentIn applies the In predicate on the "progressPercent" field.
func ProgressPercentIn(vs ...uint8) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldProgressPercent, vs...))
}

// ProgressPercentNotIn applies the NotIn predicate on the "progressPercent" field.
func ProgressPercentNotIn(vs ...uint8) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldProgressPercent, vs...))
}

// ProgressPercentGT applies the GT predicate on the "progressPercent" field.
func ProgressPercentGT(v uint8) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldProgressPercent, v))
}

// ProgressPercentGTE applies the GTE predicate on the "progressPercent" field.
func ProgressPercentGTE(v uint8) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldProgressPercent, v))
}

// ProgressPercentLT applies the LT predicate on the "progressPercent" field.
func ProgressPercentLT(v uint8) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldProgressPercent, v))
}

// ProgressPercentLTE applies the LTE predicate on the "progressPercent" field.
func ProgressPercentLTE(v uint8) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldProgressPercent, v))
}

// ProgressPercentIsNil applies the IsNil predicate on the "progressPercent" field.
func ProgressPercentIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldProgressPercent))
}

// ProgressPercentNotNil applies the NotNil predicate on the "progressPercent" field.
func ProgressPercentNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldProgressPercent))
}

// ProgressSourceEQ applies the EQ predicate on the "progressSource" field.
func ProgressSourceEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldProgressSource, v))
}

// ProgressSourceNEQ applies the NEQ predicate on the "progressSource" field.
func ProgressSourceNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldProgressSource, v))
}

// ProgressSourceIn applies the In predicate on the "progressSource" field.
func ProgressSourceIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldProgressSource, vs...))
}

// ProgressSourceNotIn applies the NotIn predicate on the "progressSource" field.
func ProgressSourceNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldProgressSource, vs...))
}

// ProgressSourceGT applies the GT predicate on the "progressSource" field.
func ProgressSourceGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldProgressSource, v))
}

// ProgressSourceGTE applies the GTE predicate on the "progressSource" field.
func ProgressSourceGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldProgressSource, v))
}

// ProgressSourceLT applies the LT predicate on the "progressSource" field.
func ProgressSourceLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldProgressSource, v))
}

// ProgressSourceLTE applies the LTE predicate on the "progressSource" field.
func ProgressSourceLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldProgressSource, v))
}

// ProgressSourceContains applies the Contains predicate on the "progressSource" field.
func ProgressSourceContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldProgressSource, v))
}

// ProgressSourceHasPrefix applies the HasPrefix predicate on the "progressSource" field.
func ProgressSourceHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldProgressSource, v))
}

// ProgressSourceHasSuffix applies the HasSuffix predicate on the "progressSource" field.
func ProgressSourceHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldProgressSource, v))
}

// ProgressSourceEqualFold applies the EqualFold predicate on the "progressSource" field.
func ProgressSourceEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldProgressSource, v))
}

// ProgressSourceContainsFold applies the ContainsFold predicate on the "progressSource" field.
func ProgressSourceContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldProgressSource, v))
}

// PlayStatusEQ applies the EQ predicate on the "playStatus" field.
func PlayStatusEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldPlayStatus, v))
}

// PlayStatusNEQ applies the NEQ predicate on the "playStatus" field.
func PlayStatusNEQ(v string) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldPlayStatus, v))
}

// PlayStatusIn applies the In predicate on the "playStatus" field.
func PlayStatusIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldPlayStatus, vs...))
}

// PlayStatusNotIn applies the NotIn predicate on the "playStatus" field.
func PlayStatusNotIn(vs ...string) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldPlayStatus, vs...))
}

// PlayStatusGT applies the GT predicate on the "playStatus" field.
func PlayStatusGT(v string) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldPlayStatus, v))
}

// PlayStatusGTE applies the GTE predicate on the "playStatus" field.
func PlayStatusGTE(v string) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldPlayStatus, v))
}

// PlayStatusLT applies the LT predicate on the "playStatus" field.
func PlayStatusLT(v string) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldPlayStatus, v))
}

// PlayStatusLTE applies the LTE predicate on the "playStatus" field.
func PlayStatusLTE(v string) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldPlayStatus, v))
}

// PlayStatusContains applies the Contains predicate on the "playStatus" field.
func PlayStatusContains(v string) predicate.Game {
	return predicate.Game(sql.FieldContains(FieldPlayStatus, v))
}

// PlayStatusHasPrefix applies the HasPrefix predicate on the "playStatus" field.
func PlayStatusHasPrefix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasPrefix(FieldPlayStatus, v))
}

// PlayStatusHasSuffix applies the HasSuffix predicate on the "playStatus" field.
func PlayStatusHasSuffix(v string) predicate.Game {
	return predicate.Game(sql.FieldHasSuffix(FieldPlayStatus, v))
}

// PlayStatusEqualFold applies the EqualFold predicate on the "playStatus" field.
func PlayStatusEqualFold(v string) predicate.Game {
	return predicate.Game(sql.FieldEqualFold(FieldPlayStatus, v))
}

// PlayStatusContainsFold applies the ContainsFold predicate on the "playStatus" field.
func PlayStatusContainsFold(v string) predicate.Game {
	return predicate.Game(sql.FieldContainsFold(FieldPlayStatus, v))
}

// IsVisibleEQ applies the EQ predicate on the "isVisible" field.
func IsVisibleEQ(v bool) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldIsVisible, v))
}

// IsVisibleNEQ applies the NEQ predicate on the "isVisible" field.
func IsVisibleNEQ(v bool) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldIsVisible, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldSort, v))
}

// SyncedAtEQ applies the EQ predicate on the "syncedAt" field.
func SyncedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "syncedAt" field.
func SyncedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "syncedAt" field.
func SyncedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "syncedAt" field.
func SyncedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "syncedAt" field.
func SyncedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "syncedAt" field.
func SyncedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "syncedAt" field.
func SyncedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "syncedAt" field.
func SyncedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldSyncedAt, v))
}

// SyncedAtIsNil applies the IsNil predicate on the "syncedAt" field.
func SyncedAtIsNil() predicate.Game {
	return predicate.Game(sql.FieldIsNull(FieldSyncedAt))
}

// SyncedAtNotNil applies the NotNil predicate on the "syncedAt" field.
func SyncedAtNotNil() predicate.Game {
	return predicate.Game(sql.FieldNotNull(FieldSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Game {
	return predicate.Game(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Game {
	return predicate.Game(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Game) predicate.Game {
	return predicate.Game(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Game) predicate.Game {
	return predicate.Game(sql.NotPredicates(p))
}
